In [56]:
def function(condition, lst):
    try:
        if condition < 1:
            print("condition < 1")
        else:
            x = 0
            while x in range(0, 3):
                if lst[x] == "":
                    print("I am here 1")
                    x = x + 1
                else:
                    print("I am here 2")
                    x = x + 1
            else:
                print("All good")
    except:
        print("error")

In [57]:
a = ["", "a", "b"]
function(1, a)

I am here 1
I am here 2
I am here 2
All good

In [58]:
c = [[(1, 2), (1, 4)], [(7, 5), (5, 4)]]
d = [(1, 1), (7, 5)], [(2, 4), (5, 4)]

In [59]:
a = []
for z, _val1 in enumerate(c):
    x = ()
    for y, _val2 in enumerate(_val1):
        x += (c[z][1], )
    a.append(x)
a

[((1, 4), (1, 4)), ((5, 4), (5, 4))]

In [60]:
import pandas as pd
import re

df_1 = pd.DataFrame(data=[{
    'Player': 'O. Fuglsang'
}, {
    'Player': 'J. Jensen-Abbew'
}, {
    'Player': 'M. Enggård'
}, {
    'Player': 'J. Liburd'
}])
df_2 = pd.DataFrame(data=[{
    'Player': 'R. Mudražija',
    'Team': 'a1',
    'Age': 'a2',
    'Value': 'a3'
}, {
    'Player': 'J. Gomez',
    'Team': 'b1',
    'Age': 'b2',
    'Value': 'b3'
}, {
    'Player': 'T. Mølgaard',
    'Team': 'c1',
    'Age': 'c2',
    'Value': 'c3'
}, {
    'Player': 'J. Liburd',
    'Team': 'd1',
    'Age': 'd2',
    'Value': 'd3'
}])
result_inner_without_regex = df_1.merge(df_2)  # by default it takes inner join


def replace_name(name):
    return re.sub('\w+\.', '', name)


df_1['Player'] = df_1['Player'].apply(replace_name)
df_2['Player'] = df_2['Player'].apply(replace_name)
result_with_regex_left = df_1.merge(
    df_2, how='left')  # player as a key because only in these table
result_with_regex_left

          Player Team  Age Value
0       Fuglsang  NaN  NaN   NaN
1   Jensen-Abbew  NaN  NaN   NaN
2        Enggård  NaN  NaN   NaN
3         Liburd   d1   d2    d3

In [61]:
class Parent:

    def __init__(self, lst):
        self.lst = lst

    def return_even(self):
        return [i for i in self.lst if i % 2 == 0]


class Child(Parent):

    def __init__(self, lst):
        Parent.__init__(self, lst)

    def return_odd(self):
        return [i for i in self.lst if i % 2 != 0]


class GrandChild(Child):

    def __init__(self, lst):
        Child.__init__(self, lst)

    def return_reverse(self):
        return self.lst[::-1]


a = '16,5,4,3,211'
a_int_lst = [int(i) for i in a.split(',')]
# prnt = Parent(a_int_lst)
# prnt.return_even()
# chld = Child(a_int_lst)
# print(chld.return_even())
# print(chld.return_odd())
gchld = GrandChild(a_int_lst)
print(gchld.return_even())
print(gchld.return_odd())
print(gchld.return_reverse())

[16, 4]
[5, 3, 211]
[211, 3, 4, 5, 16]

In [62]:
import pandas as pd

df = pd.DataFrame(data=[{
    'id': ['Adam', 'Salman', 'Mike']
}, {
    'id': ['Ali', 'Bilal', 'Ahmed']
}, {
    'id': ['Yasir', 'Undertaker', 'Johncena']
}, {
    'id': ['Sufiyan', 'Adam', 'Ahad']
}, {
    'id': ['Adam', 'Bruclee', 'BookerT']
}])


def remove_adam(lst_id):
    return [name for name in lst_id if name.lower() != 'adam']


df['id'].apply(remove_adam)

0                   [Salman, Mike]
1              [Ali, Bilal, Ahmed]
2    [Yasir, Undertaker, Johncena]
3                  [Sufiyan, Ahad]
4               [Bruclee, BookerT]
Name: id, dtype: object

In [63]:
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]})
df2 = pd.DataFrame({'A': [2, 4, 100], 'D': ['D1', 'D2', 'D3']})
df1.merge(df2)

   A   B   D
0  2  20  D1
1  4  40  D2

In [64]:
import pandas as pd

df = pd.read_csv('./Barcelona_rent_price.csv')
df[df['Average _rent'] == 'average rent (euro/month)'].groupby(
    by=['Year', 'Average _rent']).agg({'Price': 'mean'})

                                     Price
Year Average _rent
2014 average rent (euro/month)  661.639048
2015 average rent (euro/month)  695.240399
2016 average rent (euro/month)  750.959891
2017 average rent (euro/month)  829.380403
2018 average rent (euro/month)  874.052259
2019 average rent (euro/month)  923.321561
2020 average rent (euro/month)  915.921190
2021 average rent (euro/month)  871.593704
2022 average rent (euro/month)  922.546667

In [65]:
df = pd.DataFrame({
    'Year': [2001, 2001, 2001, 2001, 2002, 2002, 2002, 2002],
    'Month': ['Aug', 'Aug', 'Sep', 'Sep', 'Aug', 'Aug', 'Sep', 'Sep'],
    'Day': [1, 2, 1, 2, 1, 2, 1, 2],
    'Value': [1, 2, 3, 4, 5, 6, 7, 8]
})
pd.pivot_table(df,
               index='Year',
               columns='Month',
               values='Value',
               aggfunc='mean')

Month  Aug  Sep
Year
2001   1.5  3.5
2002   5.5  7.5

In [66]:
import xml.etree.ElementTree as ET

Label_pos = []

tree = ET.parse('./xml_stackoverflow.xml')
root = tree.getroot()

for el in root.iter('CompAttrVal'):
    name = el.get('name')
    if name == 'LabelFileName':
        Label_pos.append(el.get('Value'))
print(Label_pos)

['VW_FH267']

In [67]:
import pandas as pd

df = pd.read_csv('./police.csv')
df['stop_date'] = pd.to_datetime(df['stop_date'])
df['year'] = df['stop_date'].dt.year
last_20_years = df[df['year'] + 3 >= df['year'].max()]
last_20_years['year'].unique()
# df[df['year'] + 20  >= df['year'].max()]['year'].unique()

array([2012, 2013, 2014, 2015], dtype=int64)

In [68]:
import numpy as np  # import numpy not random python module


def probs(throws, lis):
    dice = list(range(1, 7))
    return np.random.choice(dice, throws, p=lis)


total = 0
throws = 100
lis = [0.2, 0.2, 0.2, 0.2, 0.1, 0.1]
choices_count = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0}
while total < 200:
    dice = np.random.randint(1, 6)
    choices = probs(throws, lis)
    if dice in choices:
        choices_count[dice] += 1
    total += 1

print(f'Total Steps: {total}')
print(f'Choices count: {choices_count}')

Total Steps: 200
Choices count: {1: 45, 2: 45, 3: 36, 4: 39, 5: 35, 6: 0}

In [69]:
from pyparsing import *

test = """
pci24 u2480-L0
fcs1 g4045-L1
pci25 h6045-L0
en192 v7024-L3
pci26 h6045-L1
"""

grammar_pci = Combine("pci" + Word(nums)).setResultsName("name") + Word(
    alphanums + "-").setResultsName("loc")
grammar_non_pci = Suppress(Regex(r"(?!pci).*"))

grammar = OneOrMore(
    Group(grammar_pci).setResultsName("pci_slots", listAllMatches=True)
    | grammar_non_pci,
    stopOn=StringEnd())

data = grammar.parse_string(test, parseAll=True)
print(data)
data_dict = data.as_dict()
print(data_dict)

[['pci24', 'u2480-L0'], ['pci25', 'h6045-L0'], ['pci26', 'h6045-L1']]
{'pci_slots': [{'name': 'pci24', 'loc': 'u2480-L0'}, {'name': 'pci25', 'loc': 'h6045-L0'}, {'name': 'pci26', 'loc': 'h6045-L1'}]}

In [70]:
from lxml import etree

xml_file = "./unbound_prefix.xml"
parser1 = etree.XMLParser(encoding='utf-8', recover=True)
xml_tree = etree.parse(xml_file, parser=parser1)
root = xml_tree.getroot()
for child in root:
    print(child.get('data'))

None
LS
None
None

In [71]:
import re

search_sentence = "for learning distinctive features among"
raw_sentences = [
    "methods it is possible to among recognize Instagram filters and at-",  # 01
    "tenuate the sensor pattern noise signal in images. Amerini",  # 02
    "et al. [10] introduced a CNN for learning distinctive features",  # 03
    "among social networks. for learning distinctive features among from the histogram of the discrete co-",  # 04
    "sine transform (DCT) coefficients and the noise residual of",  # 05
    "the images. Phan et al. [11] proposed a method to track mul-",  # 06
    "tiple image sharing on social networks by using a CNN for ar-",  # 07
    "chitecture able to learn",  # 08
    "et al. [10] introduced a CNN for learning distinctive features among it is possible to among recognize Instagram filters",  # 09
    "and at- tenuate xx"
]  # 10

for sentence in raw_sentences:
    result = re.findall(f'\s+({search_sentence})\s+', sentence, re.IGNORECASE)
    if len(result) > 0:
        print(result[0])
    else:
        print('no matched sentences!')

no matched sentences!
no matched sentences!
no matched sentences!
for learning distinctive features among
no matched sentences!
no matched sentences!
no matched sentences!
no matched sentences!
for learning distinctive features among
no matched sentences!

In [72]:
import pandas as pd

list1 = ['a', 'b', 'c']
list2 = ['d', 'e', 'f']


def calculate_test(b, e):
    if (not b in list1) or (not e in list2):
        #         raise ValueError("this should not happen!")
        return False
    else:
        return True


data = [['a', 'd'], ['b', 'e'], ['c', 'f'], ['g', 'h']]
df = pd.DataFrame(data, columns=['first', 'second'])
# calculate_test('b','e')  # True
try:
    df['should_all_be_true'] = df.apply(
        lambda row: calculate_test(row['first'], row['second']),
        axis=1)  # ValueError raised!
except Exception as e:
    print(e)
finally:
    print(df)

  first second  should_all_be_true
0     a      d                True
1     b      e                True
2     c      f                True
3     g      h               False

In [73]:
import pandas as pd
import numpy as np
import os

File = pd.read_excel('./data_cleansing.xlsx')
File1 = File.copy()
print(File1)


def replace_func(acct_name, billing_str):
    return acct_name.replace(billing_str, '')


File1['Account Name'] = File1.apply(
    lambda x: replace_func(x['Account Name'], x['Billing Street']), axis=1)
File1

       Account Name Billing Street
0               Ali        Karachi
1            Faisal        Karachi
2             Yasir        Karachi
3              Raja        Karachi
4              Taha        Karachi
5           Daniyal         Lahore
6      Haris Lahore         Lahore
7              Eraj         Lahore
8            Maryam         Lahore
9            Haseeb         Lahore
10          Reshail         Lahore
11  Ubaid Islamabad      Islamabad
12          Arsalan      Islamabad
13           Wissam      Islamabad

   Account Name Billing Street
0           Ali        Karachi
1        Faisal        Karachi
2         Yasir        Karachi
3          Raja        Karachi
4          Taha        Karachi
5       Daniyal         Lahore
6        Haris          Lahore
7          Eraj         Lahore
8        Maryam         Lahore
9        Haseeb         Lahore
10      Reshail         Lahore
11       Ubaid       Islamabad
12      Arsalan      Islamabad
13       Wissam      Islamabad

In [74]:
from random import randint
for i in range(8):
    for i in range(8):
        print(str(randint(0, 1)).ljust(3), end="")
    print()

1  1  0  1  0  1  1  0
1  1  1  1  1  1  0  0
0  0  1  1  0  0  0  0
1  0  0  0  1  0  1  0
1  0  1  1  0  0  1  1
0  1  0  0  0  0  1  0
1  1  1  1  1  0  1  0
1  1  0  0  1  0  1  1

In [75]:
import findspark

findspark.init()
findspark.find()
from pyspark.sql import *
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType
# findspark.find()

# create a Spark Session
spark = SparkSession.builder.appName('StackOverflowInitCap').getOrCreate()

data = [(1, "Italy"), \
        (2, "italy"), \
        (3, "USA"), \
        (4, "China"), \
        (5, "china")
        ]

# Create DataFrame
columns = ["ID", "Country"]
df = spark.createDataFrame(data=data, schema=columns)


def initCap(x):
    if x[0].islower():
        return x[0].upper() + x[1:]
    else:
        return x


upperCaseUDF = udf(lambda x: initCap(x), StringType())
df.withColumn("Country", upperCaseUDF(df.Country)) \
  .show(truncate=False)

+---+-------+
|ID |Country|
+---+-------+
|1  |Italy  |
|2  |Italy  |
|3  |USA    |
|4  |China  |
|5  |China  |
+---+-------+

In [30]:
import findspark

findspark.init()
findspark.find()
from pyspark.sql import *
from pyspark.sql.types import IntegerType, StringType, StructType, StructField

# create a Spark Session
spark = SparkSession.builder.appName('StackOverflowMultiple').getOrCreate()
newDF = [
    StructField('applianceName', StringType(), True),
    StructField('customer', StringType(), True),
    StructField('daysAgo', StringType(), True),
    StructField('countAnomaliesByDay', IntegerType(), True)
]
finalStruct = StructType(fields=newDF)
df = spark.read.csv('./pyspark_add_multiple_cols.csv',
                    schema=finalStruct,
                    header=True)
df_pivot = df \
    .groupBy('applianceName', 'customer') \
    .pivot('daysAgo') \
    .sum('countAnomaliesByDay')
df_pivot.show(truncate=False)

+-------------+--------+---+---+---+---+---+---+---+
|applianceName|customer|0  |1  |2  |3  |4  |5  |6  |
+-------------+--------+---+---+---+---+---+---+---+
|app1         |cust1   |100|200|300|400|500|600|700|
+-------------+--------+---+---+---+---+---+---+---+

In [77]:
import pandas as pd

df = pd.read_csv('./stackoverflowacctcard.csv')
def collect_card(acct_card):
    if len(str(acct_card)) != 9:
        return acct_card
    else:
        return ''
def collect_account(acct_card):
    if len(str(acct_card)) == 9:
        return acct_card
    else:
        ''
df['Card'] = df['Account / Card'].apply(collect_card)
df['Account'] = df['Account / Card'].apply(collect_account)
df.drop('Account / Card', axis=1, inplace=True)
df

    No Balance Start  Balance End  Difference             Card    Account
0    0        701.00       701.00        0.00           MASTER       None
1    0           NaN          NaN         NaN              NaN       None
2    1       2240.25      2181.45      -58.80  Algemeen/*!%@!#       None
3    9          0.00         0.00        0.00                   120989894
4    5          0.00         0.00        0.00                   159142752
5    4        300.00       300.00        0.00                   286695535
6   12         30.00        30.00        0.00                   578951057
7   13          0.00         0.00        0.00                   706602827
8    2          0.00         0.00        0.00                   735592139
9   11        250.00       229.16      -20.84                   810226753
10   3          0.00         0.00        0.00                   811695012
11   6         22.85        22.85        0.00                   818329167
12   0           NaN          NaN         NaN              NaN       None
13   2       3913.56      3813.56     -100.00          General       None
14   8         42.79        27.79      -15.00                   138738399
15   0          0.00         0.00        0.00                   646746507
16   1          2.90         2.90        0.00                   767402418
17  10        545.07       391.57     -153.50                   948214665
18   7        461.32        75.36     -385.96                   A98744534
19   0           NaN          NaN         NaN              NaN       None
20   0       8509.74      7775.64     -734.10           Totals       None

In [78]:
import pandas as pd
df_A = pd.DataFrame([
    {'Col 1': '57253,00987(4567)'},
    {'Col 1': 'asdf(78985>00987)'}
])
df_B = pd.DataFrame([
    {'Col 1': '57253', 'Col 2': 'TRUE'},
    {'Col 1': '78985', 'Col 2': 'NEGATIVE'},
    {'Col 1': '00987', 'Col 2': 'LAUGHS'},
])
def updateVal(v):
    for col_1, col_2 in df_B.values:
        if col_1 in v:
            v = v.replace(col_1, col_2)
    return v
    
df_A['Col 1'] = df_A['Col 1'].apply(updateVal)
df_A

                   Col 1
0      TRUE,LAUGHS(4567)
1  asdf(NEGATIVE>LAUGHS)

In [1]:
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
options = Options()
# options.add_argument('--disable-blink-features=AutomationControlled')
service = ChromeService(executable_path=ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
URL = 'https://gogohd.pro/download?id=MTkzNTU3&typesub=Gogoanime-SUB&title=Chainsaw+Man+Episode+1'
driver.get(URL)
links = driver.find_elements(By.TAG_NAME, "a")
download_links = []
for link in links:
    href = link.get_attribute('href')
    if href.find('download') != -1:
        download_links.append(href)
print(download_links)
driver.quit()

['https://gogodownload.net/download.php?url=aHR0cHM6LyAdeqwrwedffryretgsdFrsftrsvfsfsr9seWVpYnAdrefsdsdfwerFrefdsfrersfdsrfer36343534U0bmM3LmdvY2RuYW5pLmNvbS91c2VyMTM0Mi9lYzBiNzk3NmM1M2Q4YmY5MDU2YTYwNjdmMGY3ZTA3Ny9FUC4xLnYwLjM2MHAubXA0P3Rva2VuPTI2dlF6OFpGNGlsOEgwVE1HMzlCUVEmZXhwaXJlcz0xNjcxNzAwMzk0JmlkPTE5MzU1Nw==', 'https://gogodownload.net/download.php?url=aHR0cHM6LyURASDGHUSRFSJGYfdsffsderFStewthsfSFtrfteAdrefsdsdfwerFrefdsfrersfdsrfer36343534sdf9seWVpYnU0bmM3LmdvY2RuYW5pLmNvbS91c2VyMTM0Mi9lYzBiNzk3NmM1M2Q4YmY5MDU2YTYwNjdmMGY3ZTA3Ny9FUC4xLnYwLjQ4MHAubXA0P3Rva2VuPXVsaV9ZM29wTE5WVEwxWWlSZHpPbmcmZXhwaXJlcz0xNjcxNzAwMzk0JmlkPTE5MzU1Nw==', 'https://gogodownload.net/download.php?url=aHR0cHM6LyAawehyfcghysfdsDGDYdgdsfsdfwstdgdsgtert9URASDGHUSRFSJGYfdsffsderFStewthsfSFtrftesdfseWVpYnU0bmM3LmdvY2RuYW5pLmNvbS91c2VyMTM0Mi9lYzBiNzk3NmM1M2Q4YmY5MDU2YTYwNjdmMGY3ZTA3Ny9FUC4xLnYwLjcyMHAubXA0P3Rva2VuPXZVSURUamhEQlFIY2tYQ3RKakJFVXcmZXhwaXJlcz0xNjcxNzAwMzk0JmlkPTE5MzU1Nw==', 'https://gogodownload.net/download.php?url=aHR0cHM6LyAawehyfcghysfdsDGDYdgdsfsdfwstdgdsgtert9AdeqwrwedffryretgsdFrsftrsvfsfsrseWVpYnU0bmM3LmdvY2RuYW5pLmNvbS91c2VyMTM0Mi9lYzBiNzk3NmM1M2Q4YmY5MDU2YTYwNjdmMGY3ZTA3Ny9FUC4xLnYwLjEwODBwLm1wND90b2tlbj03SU56LV9QekFuNGF4dGNpdTY3WER3JmV4cGlyZXM9MTY3MTcwMDM5NCZpZD0xOTM1NTc=']

In [23]:
import json
shared ={
    "mts":{
        "account_id":"11111",
        "workbench":"aaaaa",
        "prefix":"zzzz"
    },
    "tsf":{
        "account_id":"22222",
        "workbench":"bbbbb",
        "prefix":"yyyy"

    }
}

role_arn = []
for x in shared:
   
    role = f"arn:aws:iam::'{shared[x]['account_id']}':role/'{shared[x]['prefix']}'_role"
    if role.find("'") != -1:
        role = role.replace("'", "")
    role_arn.append(role)

print(json.dumps(role_arn))

["arn:aws:iam::11111:role/zzzz_role", "arn:aws:iam::22222:role/yyyy_role"]

In [152]:
import pandas as pd
import re
auxdf =pd.DataFrame({'prod':['look','duck','chik']},index=['prod_team1','prod_team2','prod_team3'])

maindf = pd.DataFrame(
    {
        "col1": ["aoo", "auxdf.loc['prod_team2']", "foo"],
        "col2": ["auxdf['prod_team1']", "bla", "auxdf['prod_team3']"]
    }, index=['mar_team1', 'mar_team2', 'mar_team3']
)
def replaceFunc(col):
    c = re.findall("auxdf\.?\w*\['(.*)'\]", col)
    if len(c) > 0:
        col = c[0]
        for i, v in zip(auxdf.values, auxdf.index):
            if v == col:
                col = i[0]
    return col
maindf['col1'] = maindf['col1'].apply(replaceFunc)
maindf['col2'] = maindf['col2'].apply(replaceFunc)
maindf

           col1  col2
mar_team1   aoo  look
mar_team2  duck   bla
mar_team3   foo  chik

In [1]:
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
options = Options()
# options.add_argument('--disable-blink-features=AutomationControlled')
service = ChromeService(executable_path=ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
URL = 'https://www.kopykitab.com/'
driver.get(URL)
links = driver.find_elements(By.TAG_NAME, "a")
for link in links:
    href = link.get_attribute('href')
    print(f'Link text: {link.text}')
    print(f'Link href: {href}')
driver.quit()

[WDM] - Downloading: 100%|█████████████████████████████████████████████████████████| 6.58M/6.58M [00:43<00:00, 160kB/s]

Link text: My Library
Link href: https://www.kopykitab.com/mylibrary
Link text: Download eBook Reader
Link href: https://content.kopykitab.com/eReader.html
Link text: Login with Facebook
Link href: javascript:void(0)
Link text: Login
Link href: https://www.kopykitab.com/index.php?route=account/login
Link text: Register
Link href: https://www.kopykitab.com/index.php?route=account/register
Link text:
Link href: https://www.kopykitab.com/index.php?route=information/contact
Link text: 0
Link href: https://www.kopykitab.com/index.php?route=checkout/checkout&is_login=true
Link text:
Link href: https://www.kopykitab.com/
Link text: Live Class
Link href: https://www.kopykitab.com/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Class-9/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Class-10/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Class-11/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Class-12/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Chartered-Accountant/online-tutor-app
Link text: Ebooks
Link href: https://www.kopykitab.com/Books
Link text:
Link href: https://www.kopykitab.com/Higher-Education/Books
Link text:
Link href: https://www.kopykitab.com/Engineering/Books
Link text:
Link href: https://www.kopykitab.com/Management/Books
Link text:
Link href: https://www.kopykitab.com/Science/Books
Link text:
Link href: https://www.kopykitab.com/Medical/Books
Link text:
Link href: https://www.kopykitab.com/Agriculture/Books
Link text:
Link href: https://www.kopykitab.com/Law/Books
Link text:
Link href: https://www.kopykitab.com/Arts/Books
Link text:
Link href: https://www.kopykitab.com/Technology
Link text:
Link href: https://www.kopykitab.com/Professional-Courses/Books
Link text:
Link href: https://www.kopykitab.com/Company-Secretary/Books
Link text:
Link href: https://www.kopykitab.com/Chartered-Accountant/Books
Link text:
Link href: https://www.kopykitab.com/ICWA-CMA/Books
Link text:
Link href: https://www.kopykitab.com/Competitive-Exams/Books
Link text:
Link href: https://www.kopykitab.com/GATE/Books
Link text:
Link href: https://www.kopykitab.com/CAT/Books
Link text:
Link href: https://www.kopykitab.com/UGC-NET/Books
Link text:
Link href: https://www.kopykitab.com/CSIR-NET/Books
Link text:
Link href: https://www.kopykitab.com/IIT-JEE/Books
Link text:
Link href: https://www.kopykitab.com/NEET/Books
Link text:
Link href: https://www.kopykitab.com/Bank-Exams/Books
Link text:
Link href: https://www.kopykitab.com/Railways/Books
Link text:
Link href: https://www.kopykitab.com/School/Books
Link text:
Link href: https://www.kopykitab.com/School/Books
Link text:
Link href: https://www.kopykitab.com/Class-6/Books
Link text:
Link href: https://www.kopykitab.com/Class-7/Books
Link text:
Link href: https://www.kopykitab.com/Class-8/Books
Link text:
Link href: https://www.kopykitab.com/Class-9/Books
Link text:
Link href: https://www.kopykitab.com/Class-10/Books
Link text:
Link href: https://www.kopykitab.com/Class-11/Books
Link text:
Link href: https://www.kopykitab.com/Class-12/Books
Link text:
Link href: https://www.kopykitab.com/General-ebooks
Link text:
Link href: https://www.kopykitab.com/Leisure-Read
Link text:
Link href: https://www.kopykitab.com/eBooks-for-language-learning
Link text:
Link href: https://www.kopykitab.com/eBooks-For-Personality-Development
Link text:
Link href: https://www.kopykitab.com/Mass-Communication-And-Journalism
Link text:
Link href: https://www.kopykitab.com/mind-body-and-soul-eBooks
Link text:
Link href: https://www.kopykitab.com/eBooks-For-Cooking
Link text:
Link href: https://www.kopykitab.com/Journals-and-Magazines
Link text:
Link href: https://www.kopykitab.com/eBooks-For-Career-Development
Link text:
Link href: https://www.kopykitab.com/Free-eBooks/Books
Link text:
Link href: https://www.kopykitab.com/engineering-ebooks-free-download/Books
Link text:
Link href: https://www.kopykitab.com/eBooks-For-Free-Management-eBooks
Link text:
Link href: https://www.kopykitab.com/Science-Free-Books
Link text:
Link href: https://www.kopykitab.com/medical-ebooks-free-download
Link text:
Link href: https://www.kopykitab.com/Arts-Free-Books
Link text:
Link href: https://www.kopykitab.com/School-Free-Books
Link text:
Link href: https://www.kopykitab.com/literature-ebooks-download
Link text: Study Packages
Link href: https://www.kopykitab.com/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Higher-Education/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Engineering/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Professional-Courses/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Company-Secretary/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Chartered-Accountant/Study-Packages
Link text:
Link href: https://www.kopykitab.com/ICWA-CMA/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Competitive-Exams/Study-Packages
Link text:
Link href: https://www.kopykitab.com/GATE/Study-Packages
Link text:
Link href: https://www.kopykitab.com/IES/Study-Packages
Link text:
Link href: https://www.kopykitab.com/UGC-NET/Study-Packages
Link text:
Link href: https://www.kopykitab.com/CSIR-NET/Study-Packages
Link text:
Link href: https://www.kopykitab.com/IIT-JEE/Study-Packages
Link text:
Link href: https://www.kopykitab.com/NEET/Study-Packages
Link text:
Link href: https://www.kopykitab.com/CTET/Study-Packages
Link text:
Link href: https://www.kopykitab.com/General-Knowledge/Study-Packages
Link text:
Link href: https://www.kopykitab.com/School/Study-Packages
Link text:
Link href: https://www.kopykitab.com/School/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Class-6/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Class-7/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Class-8/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Class-9/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Class-10/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Class-11/Study-Packages
Link text:
Link href: https://www.kopykitab.com/Class-12/Study-Packages
Link text: Test Prep
Link href: https://www.kopykitab.com/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/GATE/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/CAT/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/IIT-JEE/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/NEET/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/Bank-Exams/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/Railways/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/UGC-NET/Mock-Test-Series/Test-Prep
Link text:
Link href: https://www.kopykitab.com/CSIR-NET/Mock-Test-Series/Test-Prep
Link text: Videos
Link href: https://www.kopykitab.com/Videos?sort=4
Link text:
Link href: https://www.kopykitab.com/Class-9/Videos
Link text:
Link href: https://www.kopykitab.com/Class-10/Videos
Link text:
Link href: https://www.kopykitab.com/Class-11/Videos
Link text:
Link href: https://www.kopykitab.com/Class-12/Videos
Link text:
Link href: https://www.kopykitab.com/Chartered-Accountant/Videos
Link text:
Link href: https://www.kopykitab.com/Company-Secretary/Videos
Link text:
Link href: https://www.kopykitab.com/IIT-JEE/Videos
Link text:
Link href: https://www.kopykitab.com/NEET/Videos
Link text:
Link href: https://www.kopykitab.com/Engineering/Videos
Link text: Combos
Link href: https://www.kopykitab.com/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/Class-9/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/Class-10/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/Class-11/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/Class-12/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/Chartered-Accountant/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/Company-Secretary/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/IIT-JEE/Combo-Offers
Link text:
Link href: https://www.kopykitab.com/NEET/Combo-Offers

Link text:
Link href: https://www.kopykitab.com/Engineering/Combo-Offers
Link text: Blog
Link href: https://www.kopykitab.com/blog/
Link text: Explore Now →
Link href: https://www.kopykitab.com/Books
Link text: Explore Notes →
Link href: https://www.kopykitab.com/Books/Faculty-Notes
Link text: Explore Now →
Link href: https://www.kopykitab.com/Books/Worksheet
Link text: Book your free counselling session →
Link href: https://www.kopykitab.com/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Books/Previous-Year-Papers
Link text:
Link href: https://www.kopykitab.com/Videos?sort=4
Link text: Books
Link href: https://www.kopykitab.com/Books
Link text: Notes
Link href: https://www.kopykitab.com/Books/Faculty-Notes
Link text: MCQ
Link href: https://www.kopykitab.com/Books/Worksheet
Link text: Live Class
Link href: https://www.kopykitab.com/online-tutor-app
Link text: Solved paper
Link href: https://www.kopykitab.com/Books/Previous-Year-Papers
Link text: Videos
Link href: https://www.kopykitab.com/Videos?sort=4
Link text: Contact with Tutors
Link href: https://www.kopykitab.com/online-tutor-app
Link text: View all Packs
Link href: https://www.kopykitab.com/Study-Packages
Link text: Class 10
Link href: https://www.kopykitab.com/#cat-233
Link text: Class 12
Link href: https://www.kopykitab.com/#cat-235
Link text: CSIR NET/JRF
Link href: https://www.kopykitab.com/#cat-526
Link text: UGC NET
Link href: https://www.kopykitab.com/#cat-533
Link text: CTET
Link href: https://www.kopykitab.com/#cat-484
Link text: GATE
Link href: https://www.kopykitab.com/#cat-242
Link text: IES
Link href: https://www.kopykitab.com/#cat-273
Link text: IIT JEE
Link href: https://www.kopykitab.com/#cat-243
Link text: NEET/AIPMT
Link href: https://www.kopykitab.com/#cat-244
Link text: Chartered Accountant
Link href: https://www.kopykitab.com/#cat-84
Link text: Company Secretary
Link href: https://www.kopykitab.com/#cat-83
Link text: Class 9
Link href: https://www.kopykitab.com/#cat-232
Link text:
Link href: https://www.kopykitab.com/ICSE-Class-10-Maths-and-Science-Study-Material
Link text: ₹
350
CBSE Class 10 Term II Science, Maths and Social Science Study Material
Topic Wise Study Materials
RD Sharma and RS Aggarwal Solution
Lakhmir Singh and Manjit Kaur Solution
Explore Pack →
Link href: https://www.kopykitab.com/CBSE-Class-10-Term-II-Study-Material
Link text: ₹
350
UP Board संपूर्ण विषय स्टडी गाइड कक्षा १० हिंदी मीडियम
संपूर्ण विषय स्टडी मटेरियल साहित्य भवन के द्वारा
पिछले वर्षो के प्रश्न पत्र संपूर्ण विषय
संपूर्ण विषय स्टडी मटेरियल एवं प्रैक्टिस सेट
Explore Pack →
Link href: https://www.kopykitab.com/UP-Board-Sampurna-Vishaya-Study-Guide-Kaksha-10-Hindi-mediume
Link text: ₹
350
ICSE Class 10 Maths and Science Study Material
Test Series
Subject Wise Study Material
Question Papers 2007-2020
Explore Pack →
Link href: https://www.kopykitab.com/ICSE-Class-10-Maths-and-Science-Study-Material
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-10-Term-II-Study-Material
Link text:
Link href: https://www.kopykitab.com/UP-Board-Sampurna-Vishaya-Study-Guide-Kaksha-10-Hindi-mediume
Link text:
Link href: https://www.kopykitab.com/ICSE-Class-10-Maths-and-Science-Study-Material
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Accountancy-Preparation-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Term-II-Commerce-Study-Material
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Term-II-PCB-Study-Material-l
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Term-II-PCM-Study-Material-l
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-History-Preparation-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Mathematics-Preparation-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Accountancy-Preparation-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Term-II-Commerce-Study-Material
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Term-II-PCB-Study-Material-l
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Term-II-PCM-Study-Material-l
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-History-Preparation-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Mathematics-Preparation-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-12-Accountancy-Preparation-Guide
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Chemical-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Chemical-Science-Study-Guide
Link text:
Link href: https://www.kopykitab.com/Best-CSIR-NET-Physical-Science-Study-Material
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Mathematical-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Physical-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Earth-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Chemical-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Chemical-Science-Study-Guide
Link text:
Link href: https://www.kopykitab.com/Best-CSIR-NET-Physical-Science-Study-Material
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Mathematical-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Physical-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Earth-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/CSIR-NET-Chemical-Sciences-Study-Guide-Notes
Link text:
Link href: https://www.kopykitab.com/Best-UGC-NET-Population-Studies-Study-Material
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Education-Study-Material
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Commerce-Preparation
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Psychology-Study-Guide
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Psychology-Study-Guide-1
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Education-Study-Guide
Link text:
Link href: https://www.kopykitab.com/Best-UGC-NET-Population-Studies-Study-Material
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Education-Study-Material
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Commerce-Preparation
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Psychology-Study-Guide
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Psychology-Study-Guide-1
Link text:
Link href: https://www.kopykitab.com/UGC-NET-Education-Study-Guide
Link text:
Link href: https://www.kopykitab.com/Best-UGC-NET-Population-Studies-Study-Material
Link text:
Link href: https://www.kopykitab.com/CTET-Revision-Pack
Link text:
Link href: https://www.kopykitab.com/CTET-Study-Material-For-Paper-I-II
Link text:
Link href: https://www.kopykitab.com/CTET-Revision-Pack
Link text:
Link href: https://www.kopykitab.com/CTET-Study-Material-For-Paper-I-II
Link text:
Link href: https://www.kopykitab.com/CTET-Revision-Pack
Link text:
Link href: https://www.kopykitab.com/GATE-Exam-Guide-For-Chemical-Engineering
Link text:
Link href: https://www.kopykitab.com/GATE-Electronics-and-Communications-Study-Material
Link text:
Link href: https://www.kopykitab.com/GATE-Mechanical-Study-Material
Link text:
Link href: https://www.kopykitab.com/GATE-Electrical-Study-Material
Link text:
Link href: https://www.kopykitab.com/GATE-Computer-Science-Exam-Guide
Link text:
Link href: https://www.kopykitab.com/Gate-Online-Test-Series
Link text:
Link href: https://www.kopykitab.com/GATE-Exam-Guide-For-Chemical-Engineering
Link text:
Link href: https://www.kopykitab.com/GATE-Electronics-and-Communications-Study-Material
Link text:
Link href: https://www.kopykitab.com/GATE-Mechanical-Study-Material
Link text:
Link href: https://www.kopykitab.com/GATE-Electrical-Study-Material
Link text:
Link href: https://www.kopykitab.com/GATE-Computer-Science-Exam-Guide
Link text:
Link href: https://www.kopykitab.com/Gate-Online-Test-Series
Link text:
Link href: https://www.kopykitab.com/GATE-Exam-Guide-For-Chemical-Engineering
Link text:
Link href: https://www.kopykitab.com/IES-Study-Guide-For-Electronics-Telecommunications-Engineering

Link text:
Link href: https://www.kopykitab.com/IES-Study-Guide-For-Civil-Engineering
Link text:
Link href: https://www.kopykitab.com/IES-Civil-Engineering-Study-Guide
Link text:
Link href: https://www.kopykitab.com/IES-Electronics-And-Telecommunication-Engineering-Study-Guide
Link text:
Link href: https://www.kopykitab.com/IES-Study-Guide-For-Electrical-Engineering-I
Link text:
Link href: https://www.kopykitab.com/IES-Study-guide-For-Mechanical-Engineering
Link text:
Link href: https://www.kopykitab.com/IES-Study-Guide-For-Electronics-Telecommunications-Engineering
Link text:
Link href: https://www.kopykitab.com/IES-Study-Guide-For-Civil-Engineering
Link text:
Link href: https://www.kopykitab.com/IES-Civil-Engineering-Study-Guide
Link text:
Link href: https://www.kopykitab.com/IES-Electronics-And-Telecommunication-Engineering-Study-Guide
Link text:
Link href: https://www.kopykitab.com/IES-Study-Guide-For-Electrical-Engineering-I
Link text:
Link href: https://www.kopykitab.com/IES-Study-guide-For-Mechanical-Engineering
Link text:
Link href: https://www.kopykitab.com/IES-Study-Guide-For-Electronics-Telecommunications-Engineering
Link text:
Link href: https://www.kopykitab.com/iit-jee-mains-preparation-pack
Link text:
Link href: https://www.kopykitab.com/Best-Books-Video-Mock-Test-Study-Material-For-IIT-JEE-2022-Preparation
Link text:
Link href: https://www.kopykitab.com/IIT-JEE-Mains-Preparation
Link text:
Link href: https://www.kopykitab.com/iit-jee-Advanced-preparation-pack
Link text:
Link href: https://www.kopykitab.com/iit-jee-mains-preparation-pack
Link text:
Link href: https://www.kopykitab.com/Best-Books-Video-Mock-Test-Study-Material-For-IIT-JEE-2022-Preparation
Link text:
Link href: https://www.kopykitab.com/IIT-JEE-Mains-Preparation
Link text:
Link href: https://www.kopykitab.com/iit-jee-Advanced-preparation-pack
Link text:
Link href: https://www.kopykitab.com/iit-jee-mains-preparation-pack
Link text:
Link href: https://www.kopykitab.com/NEET-AIIMS-AIPMT-Test
Link text:
Link href: https://www.kopykitab.com/Best-Books-Video-Mock-Test-Study-Material-For-NEET-2022-Preparation
Link text:
Link href: https://www.kopykitab.com/NEET-AIIMS-AIPMT-Test
Link text:
Link href: https://www.kopykitab.com/Best-Books-Video-Mock-Test-Study-Material-For-NEET-2022-Preparation
Link text:
Link href: https://www.kopykitab.com/NEET-AIIMS-AIPMT-Test
Link text:
Link href: https://www.kopykitab.com/CA-Intermediate-Study-Material-Beginner
Link text:
Link href: https://www.kopykitab.com/CA-Foundation-Study-Guide-Platinum-Pack
Link text:
Link href: https://www.kopykitab.com/CA-Intermediate-Study-Material-Super-Scorer
Link text:
Link href: https://www.kopykitab.com/CA-Foundation-Study-Guide-Diamond-Pack
Link text:
Link href: https://www.kopykitab.com/CA-Intermediate-Study-Material-Scorer
Link text:
Link href: https://www.kopykitab.com/CA-Foundation-Study-Guide-Silver-Pack
Link text:
Link href: https://www.kopykitab.com/CA-Intermediate-Study-Material-Beginner
Link text:
Link href: https://www.kopykitab.com/CA-Foundation-Study-Guide-Platinum-Pack
Link text:
Link href: https://www.kopykitab.com/CA-Intermediate-Study-Material-Super-Scorer
Link text:
Link href: https://www.kopykitab.com/CA-Foundation-Study-Guide-Diamond-Pack
Link text:
Link href: https://www.kopykitab.com/CA-Intermediate-Study-Material-Scorer
Link text:
Link href: https://www.kopykitab.com/CA-Foundation-Study-Guide-Silver-Pack
Link text:
Link href: https://www.kopykitab.com/CA-Intermediate-Study-Material-Beginner
Link text:
Link href: https://www.kopykitab.com/CS-Executive-Program-Study-Material-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Foundation-Study-Guide-Platinum-Pack
Link text:
Link href: https://www.kopykitab.com/CS-Executive-Program-Study-Material-Super-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Professional-Program-Study-Material-Super-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Foundation-Study-Guide-Diamond-Pack
Link text:
Link href: https://www.kopykitab.com/CS-Professional-Program-Study-Material-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Executive-Program-Study-Material-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Foundation-Study-Guide-Platinum-Pack
Link text:
Link href: https://www.kopykitab.com/CS-Executive-Program-Study-Material-Super-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Professional-Program-Study-Material-Super-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Foundation-Study-Guide-Diamond-Pack
Link text:
Link href: https://www.kopykitab.com/CS-Professional-Program-Study-Material-Scorer
Link text:
Link href: https://www.kopykitab.com/CS-Executive-Program-Study-Material-Scorer
Link text:
Link href: https://www.kopykitab.com/ICSE-Class-9-Mathematics-and-Science-Study-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-9-Maths-and-Science-Study-Guide-For-Term-I-and-Term-II
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-9-Study-Guide-With-Video-Lecture
Link text:
Link href: https://www.kopykitab.com/ICSE-Class-9-Mathematics-and-Science-Study-Guide
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-9-Maths-and-Science-Study-Guide-For-Term-I-and-Term-II
Link text:
Link href: https://www.kopykitab.com/CBSE-Class-9-Study-Guide-With-Video-Lecture
Link text:
Link href: https://www.kopykitab.com/ICSE-Class-9-Mathematics-and-Science-Study-Guide
Link text: Learn with Us
Link href: https://www.kopykitab.com/Study-Packages
Link text:
Link href: https://www.kopykitab.com/eBooks-for-schand-publishing
Link text:
Link href: https://www.kopykitab.com/upkar-prakashan-ebooks
Link text:
Link href: https://www.kopykitab.com/PHI-Learning-Books
Link text: Oswaal
→
Link href: https://www.kopykitab.com/Oswaal-Books
Link text: Laxmi
→
Link href: https://www.kopykitab.com/laxmi-publications-ebooks
Link text: Shuchita
→
Link href: https://www.kopykitab.com/Shuchita-Prakashan-solved-scanners-cs-ca-books-ebooks-publishers
Link text: Schand
→
Link href: https://www.kopykitab.com/eBooks-for-schand-publishing
Link text:
Link href: https://www.kopykitab.com/upkar-prakashan-ebooks
Link text:
Link href: https://www.kopykitab.com/PHI-Learning-Books
Link text:
Link href: https://www.kopykitab.com/Oswaal-Books
Link text:
Link href: https://www.kopykitab.com/laxmi-publications-ebooks
Link text:
Link href: https://www.kopykitab.com/Shuchita-Prakashan-solved-scanners-cs-ca-books-ebooks-publishers
Link text:
Link href: https://www.kopykitab.com/eBooks-for-schand-publishing
Link text:
Link href: https://www.kopykitab.com/upkar-prakashan-ebooks
Link text:
Link href: https://www.kopykitab.com/PHI-Learning-Books
Link text: Explore Books →
Link href: https://www.kopykitab.com/Professional-Courses
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-English-Core-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text: Oswaal CBSE Question Bank For Class - X Social Science (March 2021 Exam)
₹374.25
25% Off
View book   →
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-Social-Science-March-2021-Exam
Link text: Oswaal CBSE Question Bank For Class - X Science (March 2021 Exam)
₹374.25
25% Off
View book   →
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-Science-March-2021-Exam
Link text: Objective Accountancy
₹35.00
30% Off
View book   →
Link href: https://www.kopykitab.com/Objective-Accountancy-by-Dr-S-K-Singh
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-English-Language-And-Literature-March-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-Physics-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-Mathematics-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-Chemistry-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-Mathematics-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Pharmaceutical-Organic-Chemistry-II-by-Dr-K-G-Bothara

Link text:
Link href: https://www.kopykitab.com/Hf-Humming-Bird-Mathematics-Primer-A-by-Govinda-Ahuja
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-IX-Social-Science-March-Exam
Link text:
Link href: https://www.kopykitab.com/Uttarakhand-Pashupalan-Vibhag-Pashudhan-Prasar-Adhikari--Bharti-Pariksha-by-Dr-Lal-and-Jain
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-English-Core-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-Social-Science-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-Science-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Objective-Accountancy-by-Dr-S-K-Singh
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-English-Language-And-Literature-March-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-Physics-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-Mathematics-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-Chemistry-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-X-Mathematics-March-2021-Exam
Link text:
Link href: https://www.kopykitab.com/Pharmaceutical-Organic-Chemistry-II-by-Dr-K-G-Bothara
Link text:
Link href: https://www.kopykitab.com/Hf-Humming-Bird-Mathematics-Primer-A-by-Govinda-Ahuja
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-IX-Social-Science-March-Exam
Link text:
Link href: https://www.kopykitab.com/Uttarakhand-Pashupalan-Vibhag-Pashudhan-Prasar-Adhikari--Bharti-Pariksha-by-Dr-Lal-and-Jain
Link text:
Link href: https://www.kopykitab.com/Oswaal-CBSE-Question-Bank-For-Class-XII-English-Core-Chapterwise-And-Topicwise-Solved-Papers-March-2021-Exam
Link text: CAT
Link href: https://www.kopykitab.com/CAT
Link text: GATE
Link href: https://www.kopykitab.com/GATE
Link text: JEE
Link href: https://www.kopykitab.com/IIT-JEE
Link text: NEET
Link href: https://www.kopykitab.com/NEET
Link text: CTET
Link href: https://www.kopykitab.com/CTET
Link text: UGC NET
Link href: https://www.kopykitab.com/UGC-NET
Link text: Defence
Link href: https://www.kopykitab.com/Defence-Exam
Link text: IES
Link href: https://www.kopykitab.com/IES
Link text: NDA
Link href: https://www.kopykitab.com/NDA
Link text: IAS
Link href: https://www.kopykitab.com/IAS
Link text: SSC
Link href: https://www.kopykitab.com/SSC
Link text: GK
Link href: https://www.kopykitab.com/General-Knowledge
Link text: Current Affairs
Link href: https://www.kopykitab.com/Current-Affairs
Link text: CSIR NET/JRF
Link href: https://www.kopykitab.com/CSIR-NET
Link text:
Link href: https://www.kopykitab.com/Class-12
Link text:
Link href: https://www.kopykitab.com/Class-11
Link text:
Link href: https://www.kopykitab.com/Class-10
Link text:
Link href: https://www.kopykitab.com/Class-9
Link text:
Link href: https://www.kopykitab.com/Class-8
Link text:
Link href: https://www.kopykitab.com/Class-7
Link text:
Link href: https://www.kopykitab.com/CBSE
Link text:
Link href: https://www.kopykitab.com/ICSE
Link text:
Link href: https://www.kopykitab.com/ISC
Link text:
Link href: https://www.kopykitab.com/School-Entrance-Exam
Link text:
Link href: https://www.kopykitab.com/Pre-Primary
Link text:
Link href: https://www.kopykitab.com/Engineering
Link text:
Link href: https://www.kopykitab.com/Management
Link text:
Link href: https://www.kopykitab.com/Law
Link text:
Link href: https://www.kopykitab.com/Science
Link text:
Link href: https://www.kopykitab.com/Arts
Link text:
Link href: https://www.kopykitab.com/eBooks-for-B-Sc-bachelor-of-science
Link text:
Link href: https://www.kopykitab.com/B-Com
Link text:
Link href: https://www.kopykitab.com/eBooks-for-B-A-bachelor-of-arts
Link text:
Link href: https://www.kopykitab.com/B-Ed
Link text:
Link href: https://www.kopykitab.com/Agriculture
Link text:
Link href: https://www.kopykitab.com/Commerce-And-Economics
Link text:
Link href: https://www.kopykitab.com/Technology
Link text:
Link href: https://www.kopykitab.com/Medical
Link text:
Link href: https://www.kopykitab.com/RRB-JE
Link text:
Link href: https://www.kopykitab.com/RRB-Group-D
Link text:
Link href: https://www.kopykitab.com/RRB-NTPC
Link text:
Link href: https://www.kopykitab.com/RPF
Link text:
Link href: https://www.kopykitab.com/RRB-ALP
Link text:
Link href: https://www.kopykitab.com/Bank-PO
Link text:
Link href: https://www.kopykitab.com/Bank-Clerk
Link text:
Link href: https://www.kopykitab.com/Bank-SO
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Engineering/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Technology/online-tutor-app
Link text:
Link href: https://www.kopykitab.com/Engineering/online-tutor-app
Link text: NDA Exam Previous Year Papers | Download Sample Papers and 10-Years Solved Papers PDF
Link href: https://www.kopykitab.com/blog/nda-previous-year-papers/
Link text: ICAI CA Result 2021-22 | Check Your Foundation, Intermediate & Final Score Card
Link href: https://www.kopykitab.com/blog/icai-ca-result/
Link text: ICAI CA Application Form 2022 | Pre-requisites and Know How to Apply
Link href: https://www.kopykitab.com/blog/icai-ca-application-form/
Link text:
Link href: https://yourstory.com/2020/12/funding-alert-kopykitab-edtech-startup-stanford-angels/amp
Link text:
Link href: https://www.financialexpress.com/education-2/indian-higher-education-edtech-space-is-going-to-get-bigger/2226744/
Link text:
Link href: https://www.thehindu.com/education/peer-to-peer-learning-is-essential-for-students-and-teachers/article32476505.ece
Link text:
Link href: https://highereducationplus.com/pandemic-has-changed-the-way-we-consume-any-service-ceo-kopykitab/
Link text:
Link href: https://www.thenewsminute.com/article/digital-learning-startup-kopykitab-raises-undisclosed-amount-investors-138861
Link text: Class 12 Books
Link href: https://www.kopykitab.com/Class-12
Link text: Class 11 Books
Link href: https://www.kopykitab.com/Class-11
Link text: Class 10 Books
Link href: https://www.kopykitab.com/Class-10
Link text: Class 9 Books
Link href: https://www.kopykitab.com/Class-9
Link text: Oswaal Books
Link href: https://www.kopykitab.com/Oswaal-Books
Link text: CBSE
Link href: https://www.kopykitab.com/CBSE
Link text: NCERT
Link href: https://www.kopykitab.com/NCERT
Link text: Free Engineering Books
Link href: https://www.kopykitab.com/Engineering
Link text: Management Books
Link href: https://www.kopykitab.com/Management
Link text: Science Stream [BCA, MCA]
Link href: https://www.kopykitab.com/Science
Link text: Commerce & Economics Stream
Link href: https://www.kopykitab.com/Commerce-And-Economics
Link text: VTU
Link href: https://www.kopykitab.com/Visvesvaraya-Technological-University-Belgaum
Link text: RGPV
Link href: https://www.kopykitab.com/Rajiv-Gandhi-Proudyogiki-Vishwavidyalaya-Bhopal
Link text: Law Books & Notes
Link href: https://www.kopykitab.com/Law
Link text: CA Books
Link href: https://www.kopykitab.com/Chartered-Accountant
Link text: CS Books
Link href: https://www.kopykitab.com/Company-Secretary
Link text: CMA Books
Link href: https://www.kopykitab.com/ICWA-CMA
Link text: Shuchitha Prakashan
Link href: https://www.kopykitab.com/Professional-Courses/Shuchita-Prakashan
Link text: Schand Books
Link href: https://www.kopykitab.com/Schand
Link text: CA Study Packages
Link href: https://www.kopykitab.com/Chartered-Accountant/Study-Packages

Link text: CS Study Packages
Link href: https://www.kopykitab.com/Company-Secretary/Study-Packages
Link text: Railway Exams
Link href: https://www.kopykitab.com/Railways
Link text: Bank Exams
Link href: https://www.kopykitab.com/Bank-Exams
Link text: GATE Exam
Link href: https://www.kopykitab.com/GATE
Link text: IIT JEE Exam
Link href: https://www.kopykitab.com/IIT-JEE
Link text: NEET Exam
Link href: https://www.kopykitab.com/NEET
Link text: SSC Exams
Link href: https://www.kopykitab.com/SSC
Link text: UPSC Exam
Link href: https://www.kopykitab.com/UPSC
Link text: CBSE Class 12 Syllabus
Link href: https://www.kopykitab.com/blog/cbse-syllabus-for-class-12/
Link text: CBSE Class 11 Syllabus
Link href: https://www.kopykitab.com/blog/cbse-syllabus-for-class-11/
Link text: CBSE Class 10 Syllabus
Link href: https://www.kopykitab.com/blog/cbse-class-10-syllabus/
Link text: CBSE Class 9 Syllabus
Link href: https://www.kopykitab.com/blog/cbse-syllabus-for-class-9/
Link text: CBSE Class 8 Syllabus
Link href: https://www.kopykitab.com/blog/cbse-syllabus-for-class-8/
Link text: CBSE Class 7 Syllabus
Link href: https://www.kopykitab.com/blog/cbse-syllabus-for-class-7/
Link text: CBSE Class 12 Sample Papers
Link href: https://www.kopykitab.com/blog/cbse-sample-papers-for-class-12/
Link text: CBSE Class 11 Sample Papers
Link href: https://www.kopykitab.com/blog/cbse-sample-papers-for-class-11/
Link text: CBSE Class 10 Sample Papers
Link href: https://www.kopykitab.com/blog/cbse-sample-papers-for-class-10/
Link text: CBSE Class 9 Sample Papers
Link href: https://www.kopykitab.com/blog/cbse-sample-papers-for-class-9/
Link text: CBSE Class 8 Sample Papers
Link href: https://www.kopykitab.com/blog/cbse-sample-papers-for-class-8/
Link text: CBSE Class 7 Sample Papers
Link href: https://www.kopykitab.com/blog/cbse-sample-papers-for-class-7/
Link text: Class 12 NCERT Solutions
Link href: https://www.kopykitab.com/blog/ncert-solutions-for-class-12/
Link text: Class 11 NCERT Solutions
Link href: https://www.kopykitab.com/blog/ncert-solutions-for-class-11/
Link text: Class 10 NCERT Solutions
Link href: https://www.kopykitab.com/blog/ncert-solutions-for-class-10/
Link text: RD Sharma Class 10 Solutions
Link href: https://www.kopykitab.com/blog/rd-sharma-class-10-solutions-for-maths/
Link text: RS Aggarwal Class 10 Solutions
Link href: https://www.kopykitab.com/blog/cbse-class-10-maths-rs-aggarwal-solutions/
Link text: Class 9 NCERT Solutions
Link href: https://www.kopykitab.com/blog/ncert-solutions-for-class-9/
Link text: UGC NET
Link href: https://www.kopykitab.com/blog/ugc-net-exam/
Link text: CSIR NET
Link href: https://www.kopykitab.com/blog/csir-net-exam/
Link text: GATE
Link href: https://www.kopykitab.com/blog/gate-notification/
Link text: CTET
Link href: https://www.kopykitab.com/blog/ctet-exam/
Link text: Chartered Accountant
Link href: https://www.kopykitab.com/blog/ca-exam/
Link text: Company Secretary
Link href: https://www.kopykitab.com/blog/cs-executive-exam/
Link text: Nirali Prakashan Books PDF
Link href: https://www.kopykitab.com/Nirali-Prakashan
Link text: Youth Competition Books PDF
Link href: https://www.kopykitab.com/Youth-Competition-Times
Link text: Thakur Publication Books PDF
Link href: https://www.kopykitab.com/Thakur-Publication
Link text: Ratna Sagar Books PDF
Link href: https://www.kopykitab.com/Ratna-Sagar
Link text: Prashanth Publication Books PDF
Link href: https://www.kopykitab.com/Prashant-Publications
Link text: Modern ABC Books PDF
Link href: https://www.kopykitab.com/Modern-ABC
Link text: Oswaal Sample Papers for Class 12 PDF
Link href: https://www.kopykitab.com/Class-12/Oswaal-Books/Sample-Papers
Link text: Oswaal Sample Papers for Class 11 PDF
Link href: https://www.kopykitab.com/Class-11/Oswaal-Books/Sample-Papers
Link text: Oswaal Sample Papers for Class 10 PDF
Link href: https://www.kopykitab.com/Class-10/Oswaal-Books/Sample-Papers
Link text: Oswaal Sample Papers for Class 9 PDF
Link href: https://www.kopykitab.com/Class-9/Oswaal-Books/Sample-Papers
Link text: Oswaal Question Bank Class 12 PDF
Link href: https://www.kopykitab.com/Class-12/Oswaal-Books/Question-Bank
Link text: Oswaal Question Bank Class 10 PDF
Link href: https://www.kopykitab.com/Class-10/Oswaal-Books/Question-Bank
Link text: Schand Publications Books
Link href: https://www.kopykitab.com/Schand
Link text: Schand Class 12
Link href: https://www.kopykitab.com/Class-12/Schand
Link text: Schand Class 11
Link href: https://www.kopykitab.com/Class-11/Schand
Link text: Schand Class 10
Link href: https://www.kopykitab.com/Class-10/Schand
Link text: Schand Class 9
Link href: https://www.kopykitab.com/Class-9/Schand
Link text: Schand Class 8
Link href: https://www.kopykitab.com/Class-8/Schand
Link text: Class 8 Books PDF
Link href: https://www.kopykitab.com/Class-8
Link text: Class 7 Books PDF
Link href: https://www.kopykitab.com/Class-7
Link text: Class 6 Books PDF
Link href: https://www.kopykitab.com/Class-6
Link text: Class 5 Books PDF
Link href: https://www.kopykitab.com/Class-5
Link text: LKG Books PDF
Link href: https://www.kopykitab.com/eBooks-for-LKG
Link text: UKG Books PDF
Link href: https://www.kopykitab.com/eBooks-for-UKG
Link text: Download Bank PO Books
Link href: https://www.kopykitab.com/Bank-PO
Link text: Download Bank Clerk Books
Link href: https://www.kopykitab.com/Bank-Clerk
Link text: Download Bank SO Books
Link href: https://www.kopykitab.com/Bank-SO
Link text: Download Bank Apprentice Books
Link href: https://www.kopykitab.com/Bank-Apprentice
Link text: Study Materials for Bank Exams
Link href: https://www.kopykitab.com/Bank-Exams/Study-Materials
Link text: Bank Exam Previous Year Papers
Link href: https://www.kopykitab.com/Bank-Exams/Previous-Year-Papers
Link text: RRB JE Study Materials
Link href: https://www.kopykitab.com/RRB-JE/Study-Materials
Link text: RRB Group D Study Materials
Link href: https://www.kopykitab.com/RRB-Group-D/Study-Materials
Link text: RRB NTPC Study Materials
Link href: https://www.kopykitab.com/RRB-NTPC/Study-Materials
Link text: RPF Study Materials
Link href: https://www.kopykitab.com/RPF/Study-Materials
Link text: RRB ALP Study Materials
Link href: https://www.kopykitab.com/RRB-ALP/Study-Materials
Link text: Railway Exam Previous Year Papers
Link href: https://www.kopykitab.com/Railways/Previous-Year-Papers
Link text: Class 12 Study Packages
Link href: https://www.kopykitab.com/Class-12/Study-Packages
Link text: IIT JEE Study Packages
Link href: https://www.kopykitab.com/IIT-JEE/Study-Packages
Link text: GK Study Packs
Link href: https://www.kopykitab.com/General-Knowledge/Study-Packages
Link text: SSC Study Packs
Link href: https://www.kopykitab.com/SSC/Study-Packages
Link text: CS Study Packages
Link href: https://www.kopykitab.com/Company-Secretary/Study-Packages
Link text: CA Study Packages
Link href: https://www.kopykitab.com/Chartered-Accountant/Study-Packages
Link text: Mechanical Engineering Books
Link href: https://www.kopykitab.com/Mechanical-Engineering
Link text: CSE Books
Link href: https://www.kopykitab.com/Computer-Science
Link text: Civil Engineering Books
Link href: https://www.kopykitab.com/Civil-Engineering
Link text: Electrical Engineering Books
Link href: https://www.kopykitab.com/Electrical-Engineering
Link text: Information Technology Books
Link href: https://www.kopykitab.com/Information-Technology
Link text: Chemical Engineering Books
Link href: https://www.kopykitab.com/Chemical-Engineering
Link text: UGC NET Exam Books PDF
Link href: https://www.kopykitab.com/UGC-NET
Link text: CTET Exam Books PDF
Link href: https://www.kopykitab.com/CTET
Link text: CSIR NET Books PDF
Link href: https://www.kopykitab.com/CSIR-NET
Link text: SET Books PDF
Link href: https://www.kopykitab.com/Stage-Eligibility-Test
Link text: Teaching Exam Study Materials
Link href: https://www.kopykitab.com/Teaching-Exams/Study-Materials
Link text: Download IIT JEE Books PDF
Link href: https://www.kopykitab.com/IIT-JEE
Link text: Download NEET Books PDF
Link href: https://www.kopykitab.com/NEET
Link text: Download NTSE Books PDF
Link href: https://www.kopykitab.com/NTSE
Link text: Download GATE Books PDF
Link href: https://www.kopykitab.com/GATE
Link text: Download CAT Books PDF
Link href: https://www.kopykitab.com/CAT

Link text: IIT JEE Online Tutor App
Link href: https://www.kopykitab.com/IIT-JEE/online-tutor-app
Link text: Bank Exams Online Tutor App
Link href: https://www.kopykitab.com/Bank-Exams/online-tutor-app
Link text: Class 12 Online Tutor App
Link href: https://www.kopykitab.com/Class-12/online-tutor-app
Link text: Class 10 Online Tutor App
Link href: https://www.kopykitab.com/Class-10/online-tutor-app
Link text: General Competitive Exams Online Tutor
Link href: https://www.kopykitab.com/Competitive-Exams-General-eBooks-And-Mock-Tests/online-tutor-app
Link text: Engineering Free Books Download
Link href: https://www.kopykitab.com/engineering-ebooks-free-download
Link text: Medical Free Books Download
Link href: https://www.kopykitab.com/medical-ebooks-free-download
Link text: Management Free Books Download
Link href: https://www.kopykitab.com/eBooks-For-Free-Management-eBooks
Link text: School Free Books Downlaod
Link href: https://www.kopykitab.com/School-Free-Books
Link text: Commerce Free Books Download
Link href: https://www.kopykitab.com/Commerce-Free-Books
Link text: Contact Us
Link href: https://www.kopykitab.com/index.php?route=information/contact
Link text: About Us
Link href: https://www.kopykitab.com/about-us
Link text: FAQ
Link href: https://www.kopykitab.com/KopyKitab-FAQ
Link text: Privacy Policy
Link href: https://www.kopykitab.com/Kopykitab-Privacy-Policy
Link text: Terms & Conditions
Link href: https://www.kopykitab.com/Terms-and-Conditions
Link text: Media
Link href: https://www.kopykitab.com/media
Link text: Payment Information
Link href: https://www.kopykitab.com/payment-information
Link text: Refund Policy
Link href: https://www.kopykitab.com/index.php?route=product/product/returnPolicy
Link text: ICSI eLibrary
Link href: http://icsi.kopykitab.com/
Link text: Kopykitab eBook Reader
Link href: https://play.google.com/store/apps/details?id=com.kopykitab.ereader
Link text: Contact Us
Link href: https://www.kopykitab.com/index.php?route=information/contact
Link text: Site Map
Link href: https://www.kopykitab.com/index.php?route=information/sitemap
Link text: Refer & Earn
Link href: https://www.kopykitab.com/index.php?route=account/referral
Link text: My Account
Link href: https://www.kopykitab.com/index.php?route=account/account
Link text: Order History
Link href: https://www.kopykitab.com/index.php?route=account/order
Link text: Wish List
Link href: https://www.kopykitab.com/index.php?route=account/wishlist
Link text: My Library
Link href: https://www.kopykitab.com/mylibrary
Link text:
Link href: https://www.facebook.com/Kopykitab
Link text:
Link href: https://twitter.com/kopykitab
Link text:
Link href: https://www.youtube.com/channel/UCVy2STS5LnkTZiYgbhEQ_rw
Link text:
Link href: https://in.linkedin.com/company/kopykitab.com
Link text:
Link href: https://www.instagram.com/kopykitab/

In [5]:
import requests
from bs4 import BeautifulSoup
url = "https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/poznan?distanceRadius=0&market=ALL&locations=%5Bcities_6-1%5D&viewType=listing&lang=pl&searchingCriteria=sprzedaz&searchingCriteria=mieszkanie&searchingCriteria=cala-polska"
html_text = requests.get( url ).text
soup = BeautifulSoup(html_text, 'lxml') 
houses = soup.find_all('article', class_ = 'css-n8rq67 es62z2j16')
count =1 
for i in houses:
    print(i.text) 
    count += 1
count

PodbiteSprzedam mieszkaniePoznań, Stare Miasto, Piątkowo, os. Jana III Sobieskiego198 000 zł5025 zł/m²1 pokój39.4 m²Oferta prywatna
PodbiteSTYLOWY 3 pokojowy APARTAMENT z 2 balkonamiPoznań, Grunwald, ul. Ptasia749 000 zł10 912 zł/m²3 pokoje68.64 m²Manufaktura MieszkańBiuro nieruchomości
PodbitePIĘKNE mieszkanie w stylu SKANDYNAWSKIM obok WartyPoznań, Nowe Miasto, Rataje, ul. Wagrowska669 000 zł11 289 zł/m²3 pokoje59.26 m²Manufaktura MieszkańBiuro nieruchomości
Podbite53 m2 idealne pod inwestycje najlepsza lokalizacjaPoznań, wielkopolskie440 000 zł8302 zł/m²3 pokoje53 m²Oferta prywatna

5

In [10]:
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
options = Options()
options.add_argument('--disable-blink-features=AutomationControlled')
service = ChromeService(executable_path=ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
URL = 'https://www.otodom.pl/pl/oferty/sprzedaz/mieszkanie/poznan?distanceRadius=0&market=ALL&locations=%5Bcities_6-1%5D&viewType=listing&lang=pl&searchingCriteria=sprzedaz&searchingCriteria=mieszkanie&searchingCriteria=cala-polska'
driver.get(URL)
houses = driver.find_elements(By.XPATH, "//article[@class='css-n8rq67 es62z2j16']")
for i in houses:
    print(i.text) 
print(len(houses))
driver.quit()

Podbite
Nowe w idealnej, kameralnej lokalizacji-Uczelnie!
Poznań, Nowe Miasto, Rataje, os. Jagiellońskie
469 000 zł10 659 zł/m²2 pokoje44 m²
Oferta prywatna
Podbite
PIĘKNY apartament w cichej dzielnicy NARAMOWICE
Poznań, Stare Miasto, Naramowice, ul. Sielawy
699 000 zł9571 zł/m²4 pokoje73.03 m²
Manufaktura Mieszkań
Biuro nieruchomości
Podbite
ZACHWYCAJĄCE i jasne mieszkanie z 2 BALKONAMI
Poznań, Grunwald, ul. Ptasia
799 000 zł10 715 zł/m²4 pokoje74.57 m²
Manufaktura Mieszkań
Biuro nieruchomości
Podbite
FANTASTYCZNY apartament w sercu JEŻYC
Poznań, Jeżyce, ul. Jana Henryka Dąbrowskiego
849 000 zł11 858 zł/m²4 pokoje71.6 m²
Manufaktura Mieszkań
Biuro nieruchomości
Podbite
STYLOWY 3 pokojowy APARTAMENT z 2 balkonami
Poznań, Grunwald, ul. Ptasia
749 000 zł10 912 zł/m²3 pokoje68.64 m²
Manufaktura Mieszkań
Biuro nieruchomości
Podbite
PIĘKNE mieszkanie w stylu SKANDYNAWSKIM obok Warty
Poznań, Nowe Miasto, Rataje, ul. Wagrowska
669 000 zł11 289 zł/m²3 pokoje59.26 m²
Manufaktura Mieszkań
Biuro nieruchomości
Podbite
53 m2 idealne pod inwestycje najlepsza lokalizacja
Poznań, wielkopolskie
440 000 zł8302 zł/m²3 pokoje53 m²
Oferta prywatna
Podbite
3 pok wyposażone WYSOKI STANDARD taras
Poznań, Stare Miasto, Piątkowo
579 000 zł10 527 zł/m²1 pokój55 m²
Oferta prywatna
8

In [43]:
import pandas as pd 
#Reading the dataset
df = pd.read_csv('./stackoverflow_null_values_python.csv')

df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

df = df[df['year'] == 2020]
df_group = df.groupby(['month', 'item_id']).agg(n=('item_id', 'count')).reset_index()
pivot_df = pd.pivot_table(df_group, values='n', index='item_id', columns='month', fill_value=0)
# feb data
feb = pd.DataFrame(pivot_df.loc[:, [2]].to_records()).rename({'2': 'Februrary'}, axis=1)
feb

    item_id  Februrary
0       434          0
1      2011          0
2      3732          0
3      4016          0
4      4028          0
5      4243          0
6     12534          0
7     12556          0
8     13226          1
9     14532          0
10    15085          0
11    18532          0
12    18626          0
13    24022          0
14    24911          0
15    25117          0
16    26394          0
17    28057          0

In [44]:
# df_A = my_spark.read.csv('../python3_exercises/stackoverflow_pyspark_missing_df_A', header=True)
# df_A.write.saveAsTable("df_A")
# df_B = my_spark.read.csv('../python3_exercises/stackoverflow_pyspark_missing_df_B', header=True)
# df_B.write.saveAsTable("df_B")
# df_B.join(df_A, 
#           on=[df_B.column1 == df_A.column1, df_B.column2 == df_A.column2, df_B.column3 == df_A.column3],
#           how='leftanti'
#          ).show()
# df_A.join(df_B, 
#           on=[df_B.column1 == df_A.column1, df_B.column2 == df_A.column2, df_B.column3 == df_A.column3],
#           how='leftanti'
#          ).show()

In [9]:
def maximum(a,b,c):
    if a>b and a>c:
        print(a,"is largest")
    elif b>a and b>c:
        print(b,"is largest")
    else:
        print(c,"is largest")
x=int(input("enter the first number: "))
y=int(input("enter the second number: "))
z=int(input("enter the third number: "))
maximum(x,y,z)

enter the first number: 2
enter the second number: 3
enter the third number: 1
3 is largest

In [47]:
import pandas as pd
df = pd.DataFrame({'x1':[20,25],'y1':[5,8],'x2':[22,27],'y2':[10,2]})
df['x_max'] = df[['x1', 'x2']].max(axis=1)
df['y_max'] = df[['y1', 'y2']].max(axis=1)
df

   x1  y1  x2  y2
0  20   5  22  10
1  25   8  27   2

   x1  y1  x2  y2  x_max  y_max
0  20   5  22  10     22     10
1  25   8  27   2     27      8

In [73]:
# This example perfectly works for any nested dictionary
nested_dict = {
    1:{
        'name': 'ali',
        'gender': 'male',
        'friends': {
            'name': 'owais'
        }
    },
    2:{
        'name': 'eraj',
        'gender': 'female',
        'friends': {
            'name': 'maryam'
        }
    },
    3:{
        'name': 'Mojojojo',
        'gender': 'male',
        'friends': {
            'name': 'tanzeel',
            'enemies': [
                {
                    'name': 'Dexter',
                    'gender': 'male'
                },
                {
                    'name': 'ali',
                    'gender': 'male'
                }
            ]
        }
    },
    4:{
        'name': 'tanzeel',
        'gender': 'male',
        'friends': {
            'name': 'faisal',
            'project_partner': {
                'name': 'ali'
            }
        }
    },
    5:{
        'name': 'owais',
        'gender': 'male',
        'friends': {
            'name': 'ali'
        }
    },
    6:{
        'name': 'maryam',
        'gender': 'female',
        'friends': {
            'name': 'eraj'
        },
        'fyp_partners': {
            'name': 'ali'
        }
    },
}
counts_dict = {
    'ali': 0, # define your name with declaring 0 count initially
    'eraj': 0
}
# print(hasattr(nested_dict, 'items')) # items is a func of dictionary
def search_in_nested(pass_dict):   
    if isinstance(pass_dict, dict): # you can also use hasattr(pass_dict, 'items') 
        for k, v in pass_dict.items():
            if (k == 'name' and v == 'ali') or (k == 'name' and v == 'eraj'):
                counts_dict[v] += 1 # here increment by one 
            elif isinstance(v, dict):
                search_in_nested(v)
            elif isinstance(v, list): # for checking if there's a dict in a list
                for lst_item in v:
                    search_in_nested(lst_item)
search_in_nested(nested_dict)
counts_dict # ali exist 5 times and eraj 2 times in this nested dictionary

{'ali': 5, 'eraj': 2}

In [88]:
with open('stackoverflow_lines_cut_specific_word.txt') as f:
    lines = f.readlines()
print(lines)
for word in ['ali', 'superb']:
    for line in lines:
        print(line)
        if word in line:
            lines.remove(line)
with open('output.txt', 'w') as f:
    f.writelines(lines)
print(lines)

['Hello how are you\n', 'I am ali\n', 'nice to meet superb you \n', 'ali where you live\n', 'i live in karachi\n', 'ali welcome to the cloud world\n', 'your life is superb']
Hello how are you

I am ali

ali where you live

ali welcome to the cloud world

Hello how are you

nice to meet superb you

your life is superb
['Hello how are you\n', 'i live in karachi\n']

In [2]:
import re
def user():
    while True:
        print(f"Blue, Red, Gold, White, Black, Brown")
        user = input("Enter a color: ").lower()
        if len(re.findall('.?-?[0-9]+', user)) > 0:
            print("Please enter a valid input, don't pass an number value")
            continue
        if user not in ['blue', 'red', 'gold', 'white', 'black', 'brown']:
            print('Please only enter')
            continue
        else:
            break
    return user
user()

Blue, Red, Gold, White, Black, Brown
Enter a color: YELLOW
Please only enter
Blue, Red, Gold, White, Black, Brown
Enter a color: red

'red'

In [4]:
str1 = "aaa < bbb < ccc"
output = re.sub(r'(\w+) < (\w+) < (\w+)', r'\1[\2] = \3', str1)
print(output)  # aaa[bbb] = ccc

aaa[bbb] = ccc

In [3]:
def game():
    print('hello world')
    def first_check():
        player_sum = sum(player)
        dealer_sum = sum(dealer)
        if 21 in [player_sum,dealer_sum]:
            if 21 in [player_sum] and 21 in [dealer_sum]:
                print("Both you and the dealer have Blackjack, its a push!!")
        blackjack()

is_playing = True
while is_playing:
    if input("Do you want to play again? Y or N ").lower() == 'n':
        is_playing = False
        print('Game Ends...')
        continue
    game()

Do you want to play again? Y or Na
hello world
Do you want to play again? Y or Nb
hello world
Do you want to play again? Y or Na
hello world
Do you want to play again? Y or Nn
Game Ends...

update 'version="2.0.3"' to 'version="1"' in line that has <coverage<br>
rename "class" to "file"<br>
insert new "</file>" after every "" so that xml syntax is intact.<br>
rename "filename" to path<br>
rename "line" to "lineToCover"<br>
rename "number" to "lineNumber"<br>
delete all lines with "<source$" (<source, <sources)<br>

In [3]:
import re
with open('./stackoverflow_xml_replace.txt', 'r') as f:
    lines = f.readlines()
    for index, line in enumerate(lines):
        if '<coverage' in lines[index]:
            lines[index] = lines[index].replace('version="2.0.3"', 'version="1"')
        if 'class' in lines[index]:
            lines[index] = re.sub(r"\bclass\b","file",lines[index])
        if 'filename' in lines[index]:
            lines[index] = re.sub(r"\bfilename\b","path",lines[index])
        if '<line' in lines[index]:
            lines[index] = lines[index].replace('line', 'lineToCover')
        if 'number' in lines[index]:
            lines[index] = re.sub(r"\bnumber\b","lineNumber",lines[index])
        if '<source' in lines[index]:
            lines.remove(lines[index])
with open('./stackoverflow_xml_replace_output.txt', 'w') as f:
    f.writelines(lines)
print(lines)

['<?xml version="1.0" ?>\n', '<!DOCTYPE coverage\n', "  SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-04.dtd'>\n", '<coverage branch-rate="0.0" branches-covered="0" branches-valid="0" complexity="0" line-rate="0.5936254980079682" lines-covered="447" lines-valid="753" timestamp="1672197709" version="1">\n', '    <packages>\n', '        <package line-rate="0.7614678899082569" branch-rate="0.0" name="src.services.guava.keys" complexity="0">\n', '            <classes>\n', '                <file branch-rate="0.0" complexity="0" path="src/services/guava/keys/keys.go" line-rate="0.7614678899082569" name="src.services.guava.keys.keys.go">\n', '                    <methods/>\n', '                    <lineToCovers>\n', '                        <lineToCover branch="false" hits="0" lineNumber="109"/>\n', '                        <lineToCover branch="false" hits="0" lineNumber="123"/>\n', '                    </lines>\n', '                </file>\n', '            </classes>\n', '        </package>\n', '        <package line-rate="0.5944055944055944" branch-rate="0.0" name="src.services.secrets.vault" complexity="0">\n', '            <classes>\n', '                <file branch-rate="0.0" complexity="0" path="src/services/guava/vault/vault.go" line-rate="0.5944055944055944" name="src.services.guava.vault.vault.go">\n', '                    <methods/>\n', '                    <lineToCovers>\n', '                        <lineToCover branch="false" hits="1" lineNumber="251"/>\n', '                        <lineToCover branch="false" hits="1" lineNumber="253"/>\n', '                    </lines>\n', '                </file>\n', '            </classes>\n', '        </package>\n', '    </packages>\n', '</coverage>']

In [45]:
import findspark
findspark.init()
findspark.find()
from pyspark.sql import *
from  pyspark.sql.functions import *
data = [{"REGISTER_DATE": '', "FORM_DATE": '16-12-2022', "GENDER": 'Female', "Truth": True},
{"REGISTER_DATE": '13-09-2022', "FORM_DATE": '06-12-2022',"GENDER": 'Female', "Truth":True},
{"REGISTER_DATE": '', "FORM_DATE": '20-12-2022', "GENDER": 'Female', "Truth": True},
{"REGISTER_DATE": '', "FORM_DATE": '18-12-2022', "GENDER": 'Female', "Truth": True}]# Define Schema without infering spark
spark = SparkSession.builder.getOrCreate()
create_df = spark.createDataFrame(data)
print('Before converting to date and handling null')
create_df.printSchema()
create_df.show()
create_df = create_df.withColumn('FORM_DATE', to_date(col('FORM_DATE'), 'dd-MM-yyyy'))
create_df = create_df.withColumn('REGISTER_DATE', to_date(col('REGISTER_DATE'), 'dd-MM-yyyy'))
# Solution 1:
# create_df = create_df.withColumn('REGISTER_DATE',when((col('REGISTER_DATE').isNull()) & 
#     (col('FORM_DATE').isNotNull()) & (col('GENDER')== 'Female'), create_df.FORM_DATE)
#     .otherwise(create_df['REGISTER_DATE']))
# Solution 2:
create_df = create_df.withColumn('REGISTER_DATE', coalesce('REGISTER_DATE', 'FORM_DATE'))
# convert back to string 
create_df = create_df.withColumn('FORM_DATE', col('FORM_DATE').cast('string'))
create_df = create_df.withColumn('REGISTER_DATE', col('REGISTER_DATE').cast('string'))
print('After converting to date and handling null')
create_df.printSchema()
create_df.show()

Before converting to date and handling null
root
 |-- FORM_DATE: string (nullable = true)
 |-- GENDER: string (nullable = true)
 |-- REGISTER_DATE: string (nullable = true)
 |-- Truth: boolean (nullable = true)

+----------+------+-------------+-----+
| FORM_DATE|GENDER|REGISTER_DATE|Truth|
+----------+------+-------------+-----+
|16-12-2022|Female|             | true|
|06-12-2022|Female|   13-09-2022| true|
|20-12-2022|Female|             | true|
|18-12-2022|Female|             | true|
+----------+------+-------------+-----+

After converting to date and handling null
root
 |-- FORM_DATE: string (nullable = true)
 |-- GENDER: string (nullable = true)
 |-- REGISTER_DATE: string (nullable = true)
 |-- Truth: boolean (nullable = true)

+----------+------+-------------+-----+
| FORM_DATE|GENDER|REGISTER_DATE|Truth|
+----------+------+-------------+-----+
|2022-12-16|Female|   2022-12-16| true|
|2022-12-06|Female|   2022-09-13| true|
|2022-12-20|Female|   2022-12-20| true|
|2022-12-18|Female|   2022-12-18| true|
+----------+------+-------------+-----+

In [25]:
import numpy as np
def convert_2d(num_1, num_2):
    arr = np.arange(num_1, num_2 + 1)
    return (np.reshape(arr, (2, 3)) ** 2) + 5
# convert_2d(int(input('Enter no 1: ')), int(input('Enter no 2: ')))
convert_2d(2, 7)

array([[ 9, 14, 21],
       [30, 41, 54]], dtype=int32)

In [5]:
from turtle import clear

from selenium import webdriver

from selenium.webdriver.common.keys import Keys

from selenium.webdriver.common.by import By

from selenium.webdriver.support.ui import WebDriverWait

from selenium.webdriver.support import expected_conditions as EC

import time
import os

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--incognito")
driver = webdriver.Chrome(executable_path="C:/Users/Test/Downloads/chromedriver_win32/chromedriver.exe",options=chrome_options)#VariablesID1 = "slice0Flight1MainCabin"

NAME = "segments[0].orgin"

NAME1 = "segments[0].destination"

NAME2 = "segments[0].travelDate"

NAME3 = "segments[1].travelDate"

NAME4 = "closeBannerButton"

XPATH = "//*[@id='flightSearchSubmitBtn']"

XPATH2 = "//*[@id='slice0Flight1MainCabin']"

LINK_TEXT = "https://www.aa.com/booking/find-flights"

driver.get(LINK_TEXT)

print(driver.title)

time.sleep(10)

button = driver.find_element(By.NAME, NAME4)
button.click()

search = driver.find_element(By.NAME, NAME)
search.send_keys("PHX")

search = driver.find_element(By.NAME, NAME1)

search.send_keys("LHR")

search = driver.find_element(By.NAME, NAME2)

search.send_keys("09/20/23")

time.sleep(5)
search = driver.find_element(By.NAME, NAME3)

search.send_keys("09/27/23")

time.sleep(5)
button = driver.find_element(By.XPATH, XPATH)

button.click()

#Sleep timertime.sleep(45)

button = driver.find_element(By.XPATH, XPATH)

button.click()
driver.quit()

c:\users\muhammad ali\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: executable_path has been deprecated, please pass in a Service object

Book flights - Book round trip, one way, multi city - American Airlines

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="closeBannerButton"]"}
  (Session info: chrome=108.0.5359.125)
Stacktrace:
Backtrace:
	(No symbol) [0x004DF243]
	(No symbol) [0x00467FD1]
	(No symbol) [0x0035D04D]
	(No symbol) [0x0038C0B0]
	(No symbol) [0x0038C22B]
	(No symbol) [0x003BE612]
	(No symbol) [0x003A85D4]
	(No symbol) [0x003BC9EB]
	(No symbol) [0x003A8386]
	(No symbol) [0x0038163C]
	(No symbol) [0x0038269D]
	GetHandleVerifier [0x00779A22+2655074]
	GetHandleVerifier [0x0076CA24+2601828]
	GetHandleVerifier [0x00588C0A+619850]
	GetHandleVerifier [0x00587830+614768]
	(No symbol) [0x004705FC]
	(No symbol) [0x00475968]
	(No symbol) [0x00475A55]
	(No symbol) [0x0048051B]
	BaseThreadInitThunk [0x7667FEF9+25]
	RtlGetAppContainerNamedObjectPath [0x774E7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x774E7B8E+238]

In [2]:
mylist = [3, 1]
benchmark = 2
if any(ele > benchmark for ele in mylist):
    print('True')
else:
    print('False')

True

In [30]:
import pandas as pd
df = pd.DataFrame(data=[{'result': 'M'}, {'result':'B'}, {'result':'B'}, {'result':'M'}])
# Sol 1
def changeValue(r):
    if r == 'M':
        return 0
    else:
        return 1

df.apply(lambda x: changeValue(x['result']), axis=1)
# Sol 2
# df['result'].map({'M': 0, 'B': 1})

0    0
1    1
2    1
3    0
Name: result, dtype: int64

In [7]:
import pandas as pd
import re
df = pd.DataFrame(
    data=
    [
        {'emp_length': '10+years'},
        {'emp_length': '3 years'},
        {'emp_length': '<1 year'}
    ]
                 )
df['emp_length'] = df['emp_length'].str.extract(r'(\d+)')
df

  emp_length
0         10
1          3
2          1

In [17]:
from openpyxl import load_workbook
import pandas as pd
wb = load_workbook(filename = './formula_contains_raw.xlsx', ).active
print(wb.values)
# sheet_names = wb.get_sheet_names()[0]
# sheet_ranges = wb[name]
df = pd.DataFrame(list(wb.values)[1:], columns=list(wb.values)[0])
df.head()

<generator object Worksheet.values at 0x0000010514837E48>

               formulas
0                   now
1                    we
2                  =2+3
3  =_xlfn.CONCAT(A2,A3)

In [24]:
import pandas as pd
df = pd.read_csv('dirty_data.csv')
# df.to_parquet('dirty_data.parquet') # install pyarrow

In [3]:
[1 + i for i in range(1, 5)].append(2)

In [37]:
import string
def check_v_c(word):
    result = []
    for i in word:
        if i.lower() in "aeious":
            result.append(f'{i} is a vowel')
        elif i in string.punctuation:
            result.append(f'{i} is a punchuation')
        else:
            result.append(f'{i} is a consonant')
    return result
print('\n'.join(check_v_c("Mon.ey")))

M is a consonant
o is a vowel
n is a consonant
. is a punchuation
e is a vowel
y is a consonant

In [35]:
import re
phrase = "www.usatoday.com/story/travel/airline-news/2022/10/04/airplane-behaviors-reclining-seats-overhead-bins-shoes/8129315001/"

text = '/story/'       ## uses BOTH "/"
text = text.replace('/', '')
re.findall(f'\/{text}\/', phrase)

['/story/']

In [4]:
import requests
res = requests.get('https://ll.thespacedevs.com/2.0.0/launch/upcoming')
print(res.json())

{'count': 251, 'next': 'https://ll.thespacedevs.com/2.0.0/launch/upcoming/?limit=10&offset=10', 'previous': None, 'results': [{'id': '129c491b-c5df-4651-b15d-d4cbe6df7251', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/129c491b-c5df-4651-b15d-d4cbe6df7251/', 'launch_library_id': 1213, 'slug': 'proton-mblok-dm-03-elektro-l-no4', 'name': 'Proton-M/Blok DM-03 | Elektro-L No.4', 'status': {'id': 1, 'name': 'Go'}, 'net': '2023-02-05T09:12:52Z', 'window_end': '2023-02-05T09:12:52Z', 'window_start': '2023-02-05T09:12:52Z', 'inhold': False, 'tbdtime': False, 'tbddate': False, 'probability': -1, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 96, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/96/', 'name': 'Khrunichev State Research and Production Space Center', 'type': 'Government'}, 'rocket': {'id': 130, 'configuration': {'id': 46, 'launch_library_id': 62, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/46/', 'name': 'Proton-M', 'family': 'Proton / UR-500', 'full_name': 'Proton-M Blok DM-03', 'variant': 'M Blok DM-03'}}, 'mission': {'id': 6282, 'launch_library_id': None, 'name': 'Elektro-L No.4', 'description': 'Elektro-L is a series of meteorological satellites developed for the Russian Federal Space Agency by NPO Lavochkin. They are designed to capture real-time images of clouds and the Earthâ€™s underlying surface, heliogeophysical measurements, collection and translating hydrometeorological and service data.', 'launch_designator': None, 'type': 'Earth Science', 'orbit': {'id': 1, 'name': 'Geostationary Orbit', 'abbrev': 'Direct-GEO'}}, 'pad': {'id': 68, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/68/', 'agency_id': None, 'name': 'Unknown Pad', 'info_url': None, 'wiki_url': '', 'map_url': '', 'latitude': '45.92', 'longitude': '63.342', 'location': {'id': 15, 'url': 'https://ll.thespacedevs.com/2.0.0/location/15/', 'name': 'Baikonur Cosmodrome, Republic of Kazakhstan', 'country_code': 'KAZ', 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_15_20200803142517.jpg', 'total_launch_count': 1536, 'total_landing_count': 0}, 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_68_20200803143521.jpg', 'total_launch_count': 0}, 'webcast_live': False, 'image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/proton-m_image_20191211081456.jpeg', 'infographic': None, 'program': []}, {'id': '59449fa1-f709-40c0-bcad-f669b3ee48b4', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/59449fa1-f709-40c0-bcad-f669b3ee48b4/', 'launch_library_id': None, 'slug': 'falcon-9-block-5-amazonas-nexus', 'name': 'Falcon 9 Block 5 | Amazonas Nexus', 'status': {'id': 2, 'name': 'TBD'}, 'net': '2023-02-05T22:32:00Z', 'window_end': '2023-02-06T02:32:00Z', 'window_start': '2023-02-05T22:32:00Z', 'inhold': False, 'tbdtime': False, 'tbddate': False, 'probability': 65, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 121, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/121/', 'name': 'SpaceX', 'type': 'Commercial'}, 'rocket': {'id': 7724, 'configuration': {'id': 164, 'launch_library_id': 188, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/164/', 'name': 'Falcon 9', 'family': 'Falcon', 'full_name': 'Falcon 9 Block 5', 'variant': 'Block 5'}}, 'mission': {'id': 6242, 'launch_library_id': None, 'name': 'Amazonas Nexus', 'description': 'High-throughput geostationary communications satellite built by Thales Alenia Space for Hispasat.', 'launch_designator': None, 'type': 'Communications', 'orbit': {'id': 2, 'name': 'Geostationary Transfer Orbit', 'abbrev': 'GTO'}}, 'pad': {'id': 80, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/80/', 'agency_id': 121, 'name': 'Space Launch Complex 40', 'info_url': None, 'wiki_url': 'https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_40', 'map_url': 'http://maps.google.com/maps?q=28.56194122,-80.57735736', 'latitude': '28.56194122', 'longitude': '-80.57735736', 'location': {'id': 12, 'url': 'https://ll.thespacedevs.com/2.0.0/location/12/', 'name': 'Cape Canaveral, FL, USA', 'country_code': 'USA', 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg', 'total_launch_count': 872, 'total_landing_count': 32}, 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_80_20200803143323.jpg', 'total_launch_count': 167}, 'webcast_live': False, 'image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/falcon_9_block__image_20210506060831.jpg', 'infographic': None, 'program': []}, {'id': 'f611b883-4ad3-48c6-b2ee-ececc5d8234a', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/f611b883-4ad3-48c6-b2ee-ececc5d8234a/', 'launch_library_id': None, 'slug': 'soyuz-21a-progress-ms-22-83p', 'name': 'Soyuz 2.1a | Progress MS-22 (83P)', 'status': {'id': 1, 'name': 'Go'}, 'net': '2023-02-09T06:15:36Z', 'window_end': '2023-02-09T06:15:36Z', 'window_start': '2023-02-09T06:15:36Z', 'inhold': False, 'tbdtime': False, 'tbddate': False, 'probability': None, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 63, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/63/', 'name': 'Russian Federal Space Agency (ROSCOSMOS)', 'type': 'Government'}, 'rocket': {'id': 7465, 'configuration': {'id': 24, 'launch_library_id': 49, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/24/', 'name': 'Soyuz 2.1a', 'family': 'Soyuz', 'full_name': 'Soyuz 2.1a', 'variant': ''}}, 'mission': {'id': 5864, 'launch_library_id': None, 'name': 'Progress MS-22 (83P)', 'description': 'Progress resupply mission to the International Space Station.', 'launch_designator': None, 'type': 'Resupply', 'orbit': {'id': 8, 'name': 'Low Earth Orbit', 'abbrev': 'LEO'}}, 'pad': {'id': 20, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/20/', 'agency_id': None, 'name': '31/6', 'info_url': None, 'wiki_url': 'https://en.wikipedia.org/wiki/Baikonur_Cosmodrome_Site_31', 'map_url': 'http://maps.google.com/maps?q=45.996+N,+63.564+E', 'latitude': '45.996034', 'longitude': '63.564003', 'location': {'id': 15, 'url': 'https://ll.thespacedevs.com/2.0.0/location/15/', 'name': 'Baikonur Cosmodrome, Republic of Kazakhstan', 'country_code': 'KAZ', 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_15_20200803142517.jpg', 'total_launch_count': 1536, 'total_landing_count': 0}, 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_20_20200803143516.jpg', 'total_launch_count': 405}, 'webcast_live': False, 'image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/soyuz_2.1a_image_20201013143850.jpg', 'infographic': None, 'program': [{'id': 17, 'url': 'https://ll.thespacedevs.com/2.0.0/program/17/', 'name': 'International Space Station', 'description': 'The International Space Station programme is tied together by a complex set of legal, political and financial agreements between the sixteen nations involved in the project, governing ownership of the various components, rights to crewing and utilization, and responsibilities for crew rotation and resupply of the International Space Station. It was conceived in 1984 by President Ronald Reagan, during the Space Station Freedom project as it was originally called.', 'agencies': [{'id': 16, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/16/', 'name': 'Canadian Space Agency', 'type': 'Government'}, {'id': 27, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/27/', 'name': 'European Space Agency', 'type': 'Multinational'}, {'id': 37, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/37/', 'name': 'Japan Aerospace Exploration Agency', 'type': 'Government'}, {'id': 44, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/44/', 'name': 'National Aeronautics and Space Administration', 'type': 'Government'}, {'id': 63, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/63/', 'name': 'Russian Federal Space Agency (ROSCOSMOS)', 'type': 'Government'}], 'image_url': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/international2_program_20201129184745.png', 'start_date': '1998-11-20T06:40:00Z', 'end_date': None, 'info_url': 'https://www.nasa.gov/mission_pages/station/main/index.html', 'wiki_url': 'https://en.wikipedia.org/wiki/International_Space_Station_programme'}]}, {'id': '58eba6fc-307a-4c47-b68d-aa75db6eddea', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/58eba6fc-307a-4c47-b68d-aa75db6eddea/', 'launch_library_id': None, 'slug': 'sslv-microsat-demo-2', 'name': 'SSLV | Microsat (Demo 2)', 'status': {'id': 2, 'name': 'TBD'}, 'net': '2023-02-10T03:30:00Z', 'window_end': '2023-02-10T07:30:00Z', 'window_start': '2023-02-10T03:30:00Z', 'inhold': False, 'tbdtime': False, 'tbddate': False, 'probability': None, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 31, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/31/', 'name': 'Indian Space Research Organization', 'type': 'Government'}, 'rocket': {'id': 7755, 'configuration': {'id': 150, 'launch_library_id': 189, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/150/', 'name': 'SSLV', 'family': '', 'full_name': 'SSLV', 'variant': ''}}, 'mission': {'id': 687, 'launch_library_id': 856, 'name': 'SSLV Demo 2', 'description': 'Second test flight of Indian SSLV (Small Satellite Launch Vehicle).', 'launch_designator': None, 'type': 'Test Flight', 'orbit': {'id': 8, 'name': 'Low Earth Orbit', 'abbrev': 'LEO'}}, 'pad': {'id': 50, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/50/', 'agency_id': 31, 'name': 'Satish Dhawan Space Centre First Launch Pad', 'info_url': None, 'wiki_url': 'https://en.wikipedia.org/wiki/Satish_Dhawan_Space_Centre_First_Launch_Pad', 'map_url': 'https://www.google.com/maps?q=13.733,80.235', 'latitude': '13.733', 'longitude': '80.235', 'location': {'id': 14, 'url': 'https://ll.thespacedevs.com/2.0.0/location/14/', 'name': 'Sriharikota, Republic of India', 'country_code': 'IND', 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_14_20200803142403.jpg', 'total_launch_count': 83, 'total_landing_count': 0}, 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_50_20200803143457.jpg', 'total_launch_count': 53}, 'webcast_live': False, 'image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/sslv_image_20220912001724.jpeg', 'infographic': None, 'program': []}, {'id': '3bd674c9-b689-40c4-bfe2-844c71e40844', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/3bd674c9-b689-40c4-bfe2-844c71e40844/', 'launch_library_id': None, 'slug': 'falcon-9-block-5-starlink-group-5-4', 'name': 'Falcon 9 Block 5 | Starlink Group 5-4', 'status': {'id': 2, 'name': 'TBD'}, 'net': '2023-02-11T00:00:00Z', 'window_end': '2023-02-11T00:00:00Z', 'window_start': '2023-02-11T00:00:00Z', 'inhold': False, 'tbdtime': False, 'tbddate': False, 'probability': None, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 121, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/121/', 'name': 'SpaceX', 'type': 'Commercial'}, 'rocket': {'id': 7739, 'configuration': {'id': 164, 'launch_library_id': 188, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/164/', 'name': 'Falcon 9', 'family': 'Falcon', 'full_name': 'Falcon 9 Block 5', 'variant': 'Block 5'}}, 'mission': {'id': 6257, 'launch_library_id': None, 'name': 'Starlink Group 5-4', 'description': "A batch of satellites for Starlink mega-constellation - SpaceX's project for space-based Internet communication system.", 'launch_designator': None, 'type': 'Communications', 'orbit': {'id': 8, 'name': 'Low Earth Orbit', 'abbrev': 'LEO'}}, 'pad': {'id': 80, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/80/', 'agency_id': 121, 'name': 'Space Launch Complex 40', 'info_url': None, 'wiki_url': 'https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_40', 'map_url': 'http://maps.google.com/maps?q=28.56194122,-80.57735736', 'latitude': '28.56194122', 'longitude': '-80.57735736', 'location': {'id': 12, 'url': 'https://ll.thespacedevs.com/2.0.0/location/12/', 'name': 'Cape Canaveral, FL, USA', 'country_code': 'USA', 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg', 'total_launch_count': 872, 'total_landing_count': 32}, 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_80_20200803143323.jpg', 'total_launch_count': 167}, 'webcast_live': False, 'image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20221222092248.png', 'infographic': None, 'program': []}, {'id': '13439df6-e99b-42b3-ab82-c0a8a2afe4d1', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/13439df6-e99b-42b3-ab82-c0a8a2afe4d1/', 'launch_library_id': 1981, 'slug': 'h3-22-alos-3-maiden-flight', 'name': 'H3-22 | ALOS-3 (Maiden flight)', 'status': {'id': 1, 'name': 'Go'}, 'net': '2023-02-13T01:37:55Z', 'window_end': '2023-02-13T01:44:15Z', 'window_start': '2023-02-13T01:37:55Z', 'inhold': False, 'tbdtime': True, 'tbddate': True, 'probability': -1, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 98, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/98/', 'name': 'Mitsubishi Heavy Industries', 'type': 'Commercial'}, 'rocket': {'id': 2538, 'configuration': {'id': 486, 'launch_library_id': None, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/486/', 'name': 'H3-22', 'family': 'H3', 'full_name': 'H3-22', 'variant': '22'}}, 'mission': {'id': 6089, 'launch_library_id': None, 'name': 'ALOS-3 (Maiden flight)', 'description': 'Maiden flight of the H3 launch vehicle, carrying the Advanced Land Observing Satellite-3 (ALOS-3).', 'launch_designator': None, 'type': 'Earth Science', 'orbit': {'id': 17, 'name': 'Sun-Synchronous Orbit', 'abbrev': 'SSO'}}, 'pad': {'id': 41, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/41/', 'agency_id': 37, 'name': 'Yoshinobu Launch Complex', 'info_url': None, 'wiki_url': 'https://en.wikipedia.org/wiki/Yoshinobu_Launch_Complex', 'map_url': 'https://www.google.com/maps/place/30Â°24\'08.0"N+130Â°58\'30.0"E/', 'latitude': '30.402222', 'longitude': '130.975', 'location': {'id': 26, 'url': 'https://ll.thespacedevs.com/2.0.0/location/26/', 'name': 'Tanegashima, Japan', 'country_code': 'JPN', 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_26_20200803142507.jpg', 'total_launch_count': 85, 'total_landing_count': 0}, 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_41_20200803143551.jpg', 'total_launch_count': 40}, 'webcast_live': False, 'image': None, 'infographic': None, 'program': []}, {'id': 'd6e60f3b-21d0-44f9-be02-fe0c00289b6a', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/d6e60f3b-21d0-44f9-be02-fe0c00289b6a/', 'launch_library_id': None, 'slug': 'falcon-9-block-5-inmarsat-6-f2', 'name': 'Falcon 9 Block 5 | Inmarsat-6 F2', 'status': {'id': 2, 'name': 'TBD'}, 'net': '2023-02-18T00:00:00Z', 'window_end': '2023-02-18T00:00:00Z', 'window_start': '2023-02-18T00:00:00Z', 'inhold': False, 'tbdtime': False, 'tbddate': False, 'probability': None, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 121, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/121/', 'name': 'SpaceX', 'type': 'Commercial'}, 'rocket': {'id': 7703, 'configuration': {'id': 164, 'launch_library_id': 188, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/164/', 'name': 'Falcon 9', 'family': 'Falcon', 'full_name': 'Falcon 9 Block 5', 'variant': 'Block 5'}}, 'mission': {'id': 6221, 'launch_library_id': None, 'name': 'Inmarsat-6 F2', 'description': "Inmarsat-6 is the sixth generation of satellites for the London-based global mobile satellite communications operator Inmarsat. It consists of a dual mission to augment both L-band and Ka-band Global Xpress services.\r\n\r\nAirbus Defence and Space has been awarded a contract by Inmarsat to design and develop the first two Inmarsat-6 (I-6) mobile communications satellites, creating the most versatile mobile services satellites in its fleet.\r\n\r\nThe two I-6 satellites are based on Airbus Defence and Space's Eurostar platform in its E3000e variant, which exclusively uses electric propulsion for orbit raising. The satellites take advantage of the reduction in mass that this electric propulsion technology enables for a dual payload mission, with an exceptionally large next generation digitally processed payload.\r\n\r\nI-6 F1 and F2 both carry a large 9 m aperture L-band antenna and nine multibeam Ka-band antennas, and feature a high level of flexibility and connectivity. A new generation modular digital processor provides full routing flexibility over up to 8000 channels and dynamic power allocation to over 200 spot beams in L-band. Ka-band spot beams are steerable over the full Earth disk, with flexible channel to beam allocation.", 'launch_designator': None, 'type': 'Communications', 'orbit': {'id': 2, 'name': 'Geostationary Transfer Orbit', 'abbrev': 'GTO'}}, 'pad': {'id': 72, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/72/', 'agency_id': None, 'name': 'Unknown Pad', 'info_url': None, 'wiki_url': '', 'map_url': '', 'latitude': '28.458', 'longitude': '-80.528', 'location': {'id': 12, 'url': 'https://ll.thespacedevs.com/2.0.0/location/12/', 'name': 'Cape Canaveral, FL, USA', 'country_code': 'USA', 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg', 'total_launch_count': 872, 'total_landing_count': 32}, 'map_image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_72_20200803143403.jpg', 'total_launch_count': 0}, 'webcast_live': False, 'image': 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/falcon_9_block__image_20210506060831.jpg', 'infographic': None, 'program': []}, {'id': 'e3290e0e-d967-4a5d-95eb-f8fae06a9034', 'url': 'https://ll.thespacedevs.com/2.0.0/launch/e3290e0e-d967-4a5d-95eb-f8fae06a9034/', 'launch_library_id': None, 'slug': 'soyuz-21a-soyuz-ms-23', 'name': 'Soyuz 2.1a | Soyuz MS-23', 'status': {'id': 1, 'name': 'Go'}, 'net': '2023-02-20T01:57:00Z', 'window_end': '2023-02-20T01:57:00Z', 'window_start': '2023-02-20T01:57:00Z', 'inhold': False, 'tbdtime': False, 'tbddate': False, 'probability': None, 'holdreason': '', 'failreason': '', 'hashtag': None, 'launch_service_provider': {'id': 63, 'url': 'https://ll.thespacedevs.com/2.0.0/agencies/63/', 'name': 'Russian Federal Space Agency (ROSCOSMOS)', 'type': 'Government'}, 'rocket': {'id': 7504, 'configuration': {'id': 24, 'launch_library_id': 49, 'url': 'https://ll.thespacedevs.com/2.0.0/config/launcher/24/', 'name': 'Soyuz 2.1a', 'family': 'Soyuz', 'full_name': 'Soyuz 2.1a', 'variant': ''}}, 'mission': {'id': 5914, 'launch_library_id': None, 'name': 'Soyuz MS-23', 'description': 'Soyuz MS-23 will fly without crew to the International Space Station from the Baikonur Cosmodrome in Kazakhstan to replace Soyuz MS-22, that suffered a thermal control system depressurization/leak on the ISS on December 15, 2022.', 'launch_designator': None, 'type': 'Human Exploration', 'orbit': {'id': 8, 'name': 'Low Earth Orbit', 'abbrev': 'LEO'}}, 'pad': {'id': 20, 'url': 'https://ll.thespacedevs.com/2.0.0/pad/20/', 'agency_id': None, 'name': '31/6', 'info_url': None, 'wiki_url': 'https://en.wikipedia.org/wiki/Baikonur_Cosmodrome_Site_31', 'map_url': 'http://maps.google.com/maps?q=45.996+N,+63.564+E', 'latitude': '45.996034', 'longitude': '63

In [15]:
import pandas as pd

groceries = {
    'grocery': [
        "Tesco's wafers", "Asda's shortbread", "Aldi's lemon tea",
        "Sainsbury's croissant", "Morrison's doughnut",
        "Amazon fresh's peppermint tea", "Bar becan's pizza",
        "Pound savers' shower gel"
    ],
    'category': [
        'biscuit', 'biscuit', 'tea', 'bakery', 'bakery', 'tea', 'bakery',
        'hygiene'
    ],
    'price': [0.99, 1.24, 1.89, 0.75, 0.50, 2.5, 4.99, 2]
}

df = pd.DataFrame(groceries)
# split it with "'" comma and then start it with from 1 index of a string 
# if multiple conditions for grocery string then 

# def grocery_chng(x):
#     # specify multiple conditions to replace a string
#     return x
# df['grocery'] = df['grocery'].apply(grocery_chng)

df['grocery'] = df['grocery'].apply(lambda x: x.split("'")[1][1:].title())
df

           grocery category  price
0           Wafers  biscuit   0.99
1       Shortbread  biscuit   1.24
2        Lemon Tea      tea   1.89
3        Croissant   bakery   0.75
4         Doughnut   bakery   0.50
5   Peppermint Tea      tea   2.50
6            Pizza   bakery   4.99
7       Shower Gel  hygiene   2.00

In [33]:
import pandas as pd
d = {
  "foo": [
    50,
    100
  ],
  "bar": [
    5,
    10
  ],
  "noto": [
      11,
      30
  ]
}
df_1 = pd.DataFrame(
    {
        "keys": d.keys(),
        "vals": d.values()
    }
)
df_1
df_2 = pd.DataFrame(
    {
        "item": ["foo", "bar", "noto"],
        "price": [65, 7, 33]
    }
)
main_df = df_1.merge(df_2, left_on='keys', right_on="item")
def check_price(x):
    return x['price'] >= x['vals'][0] and x['price'] <= x['vals'][1]
main_df[main_df.apply(lambda x: check_price(x), axis=1)]

  keys       vals item  price
0  foo  [50, 100]  foo     65
1  bar    [5, 10]  bar      7

In [39]:
data = {
    'Date_Time': [
        '2017-08-08 23:55:01', '2017-08-08 23:50:01', '2017-08-08 06:45:01',
        '2017-08-08 05:40:01', '2017-08-08 00:35:01',
        '2017-07-26 00:23:57', '2017-07-26 00:18:57', '2017-07-26 07:13:57',
        '2017-07-26 00:08:57', '2017-07-26 07:03:57'
    ],
    'Level': [239.0, 242.0, 246.0, 250.0, 254.0, 72.0, 67.0, 64.0, 64.0, 65.0]
}

df = pd.DataFrame(data, columns=['Date_Time', 'Level'])
df['Date_Time'] = pd.to_datetime(df['Date_Time'])
df = df.set_index('Date_Time')
df['period'] = pd.cut(
    df.index.hour,
    bins=[0, 6, 23.99],
    labels=['00:00:00 - 06:00:00', '06:00:01 - 23:59:99'],
    include_lowest=True
)
df.groupby([df.index.date, 'period'])['Level'].mean().reset_index()

      level_0               period       Level
0  2017-07-26  00:00:00 - 06:00:00   67.666667
1  2017-07-26  06:00:01 - 23:59:99   64.500000
2  2017-08-08  00:00:00 - 06:00:00  250.000000
3  2017-08-08  06:00:01 - 23:59:99  240.500000